# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "ring"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_ring_faceRingBase_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(28.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(11.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(13.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(12.5570, 3.3646, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(11.2583, 6.5000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(9.1924, 9.1924, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(6.5000, 11.2583, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(3.3646, 12.5570, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(0.0000, 13.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr9():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-3.3646, 12.5570, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr10():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-6.5000, 11.2583, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr11():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-9.1924, 9.1924, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr12():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-11.2583, 6.5000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr13():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-12.5570, 3.3646, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr14():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-13.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr15():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-12.5570, -3.3646, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr16():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-11.2583, -6.5000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr17():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-9.1924, -9.1924, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr18():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-6.5000, -11.2583, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr19():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-3.3646, -12.5570, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr20():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-0.0000, -13.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr21():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(3.3646, -12.5570, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr22():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(6.5000, -11.2583, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr23():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(9.1924, -9.1924, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr24():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(11.2583, -6.5000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingBase_Fa0_Ctr25():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(12.5570, -3.3646, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_ring_faceRingBase_Fa0():
	FC000 = ctr_face_ring_faceRingBase_Fa0_Ctr0()
	FC001 = ctr_face_ring_faceRingBase_Fa0_Ctr1()
	FC002 = ctr_face_ring_faceRingBase_Fa0_Ctr2()
	FC003 = ctr_face_ring_faceRingBase_Fa0_Ctr3()
	FC004 = ctr_face_ring_faceRingBase_Fa0_Ctr4()
	FC005 = ctr_face_ring_faceRingBase_Fa0_Ctr5()
	FC006 = ctr_face_ring_faceRingBase_Fa0_Ctr6()
	FC007 = ctr_face_ring_faceRingBase_Fa0_Ctr7()
	FC008 = ctr_face_ring_faceRingBase_Fa0_Ctr8()
	FC009 = ctr_face_ring_faceRingBase_Fa0_Ctr9()
	FC010 = ctr_face_ring_faceRingBase_Fa0_Ctr10()
	FC011 = ctr_face_ring_faceRingBase_Fa0_Ctr11()
	FC012 = ctr_face_ring_faceRingBase_Fa0_Ctr12()
	FC013 = ctr_face_ring_faceRingBase_Fa0_Ctr13()
	FC014 = ctr_face_ring_faceRingBase_Fa0_Ctr14()
	FC015 = ctr_face_ring_faceRingBase_Fa0_Ctr15()
	FC016 = ctr_face_ring_faceRingBase_Fa0_Ctr16()
	FC017 = ctr_face_ring_faceRingBase_Fa0_Ctr17()
	FC018 = ctr_face_ring_faceRingBase_Fa0_Ctr18()
	FC019 = ctr_face_ring_faceRingBase_Fa0_Ctr19()
	FC020 = ctr_face_ring_faceRingBase_Fa0_Ctr20()
	FC021 = ctr_face_ring_faceRingBase_Fa0_Ctr21()
	FC022 = ctr_face_ring_faceRingBase_Fa0_Ctr22()
	FC023 = ctr_face_ring_faceRingBase_Fa0_Ctr23()
	FC024 = ctr_face_ring_faceRingBase_Fa0_Ctr24()
	FC025 = ctr_face_ring_faceRingBase_Fa0_Ctr25()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008, FC009, FC010, FC011, FC012, FC013, FC014, FC015, FC016, FC017, FC018, FC019, FC020, FC021, FC022, FC023, FC024, FC025])
	rOneFace.check()
	return rOneFace

def ring_faceRingBase():
	FA000 = face_ring_faceRingBase_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_ring_faceRingTeeth_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(28.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_faceRingTeeth_Fa0_Ctr1():
	P000 = App.Vector(24.0000, 0.0000, 0)
	P001 = App.Vector(20.8850, 2.1951, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(23.4755, 4.9899, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(19.9722, 6.4894, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(21.9251, 9.7617, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(18.1865, 10.5000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(19.4164, 14.1068, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(15.6060, 14.0517, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(16.0591, 17.8355, 0)
	S007 = Part.LineSegment(P007, P008)
	P009 = App.Vector(12.3435, 16.9894, 0)
	S008 = Part.LineSegment(P008, P009)
	P010 = App.Vector(12.0000, 20.7846, 0)
	S009 = Part.LineSegment(P009, P010)
	P011 = App.Vector(8.5415, 19.1845, 0)
	S010 = Part.LineSegment(P010, P011)
	P012 = App.Vector(7.4164, 22.8254, 0)
	S011 = Part.LineSegment(P011, P012)
	P013 = App.Vector(4.3661, 20.5411, 0)
	S012 = Part.LineSegment(P012, P013)
	P014 = App.Vector(2.5087, 23.8685, 0)
	S013 = Part.LineSegment(P013, P014)
	P015 = App.Vector(0.0000, 21.0000, 0)
	S014 = Part.LineSegment(P014, P015)
	P016 = App.Vector(-2.5087, 23.8685, 0)
	S015 = Part.LineSegment(P015, P016)
	P017 = App.Vector(-4.3661, 20.5411, 0)
	S016 = Part.LineSegment(P016, P017)
	P018 = App.Vector(-7.4164, 22.8254, 0)
	S017 = Part.LineSegment(P017, P018)
	P019 = App.Vector(-8.5415, 19.1845, 0)
	S018 = Part.LineSegment(P018, P019)
	P020 = App.Vector(-12.0000, 20.7846, 0)
	S019 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-12.3435, 16.9894, 0)
	S020 = Part.LineSegment(P020, P021)
	P022 = App.Vector(-16.0591, 17.8355, 0)
	S021 = Part.LineSegment(P021, P022)
	P023 = App.Vector(-15.6060, 14.0517, 0)
	S022 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-19.4164, 14.1068, 0)
	S023 = Part.LineSegment(P023, P024)
	P025 = App.Vector(-18.1865, 10.5000, 0)
	S024 = Part.LineSegment(P024, P025)
	P026 = App.Vector(-21.9251, 9.7617, 0)
	S025 = Part.LineSegment(P025, P026)
	P027 = App.Vector(-19.9722, 6.4894, 0)
	S026 = Part.LineSegment(P026, P027)
	P028 = App.Vector(-23.4755, 4.9899, 0)
	S027 = Part.LineSegment(P027, P028)
	P029 = App.Vector(-20.8850, 2.1951, 0)
	S028 = Part.LineSegment(P028, P029)
	P030 = App.Vector(-24.0000, 0.0000, 0)
	S029 = Part.LineSegment(P029, P030)
	P031 = App.Vector(-20.8850, -2.1951, 0)
	S030 = Part.LineSegment(P030, P031)
	P032 = App.Vector(-23.4755, -4.9899, 0)
	S031 = Part.LineSegment(P031, P032)
	P033 = App.Vector(-19.9722, -6.4894, 0)
	S032 = Part.LineSegment(P032, P033)
	P034 = App.Vector(-21.9251, -9.7617, 0)
	S033 = Part.LineSegment(P033, P034)
	P035 = App.Vector(-18.1865, -10.5000, 0)
	S034 = Part.LineSegment(P034, P035)
	P036 = App.Vector(-19.4164, -14.1068, 0)
	S035 = Part.LineSegment(P035, P036)
	P037 = App.Vector(-15.6060, -14.0517, 0)
	S036 = Part.LineSegment(P036, P037)
	P038 = App.Vector(-16.0591, -17.8355, 0)
	S037 = Part.LineSegment(P037, P038)
	P039 = App.Vector(-12.3435, -16.9894, 0)
	S038 = Part.LineSegment(P038, P039)
	P040 = App.Vector(-12.0000, -20.7846, 0)
	S039 = Part.LineSegment(P039, P040)
	P041 = App.Vector(-8.5415, -19.1845, 0)
	S040 = Part.LineSegment(P040, P041)
	P042 = App.Vector(-7.4164, -22.8254, 0)
	S041 = Part.LineSegment(P041, P042)
	P043 = App.Vector(-4.3661, -20.5411, 0)
	S042 = Part.LineSegment(P042, P043)
	P044 = App.Vector(-2.5087, -23.8685, 0)
	S043 = Part.LineSegment(P043, P044)
	P045 = App.Vector(-0.0000, -21.0000, 0)
	S044 = Part.LineSegment(P044, P045)
	P046 = App.Vector(2.5087, -23.8685, 0)
	S045 = Part.LineSegment(P045, P046)
	P047 = App.Vector(4.3661, -20.5411, 0)
	S046 = Part.LineSegment(P046, P047)
	P048 = App.Vector(7.4164, -22.8254, 0)
	S047 = Part.LineSegment(P047, P048)
	P049 = App.Vector(8.5415, -19.1845, 0)
	S048 = Part.LineSegment(P048, P049)
	P050 = App.Vector(12.0000, -20.7846, 0)
	S049 = Part.LineSegment(P049, P050)
	P051 = App.Vector(12.3435, -16.9894, 0)
	S050 = Part.LineSegment(P050, P051)
	P052 = App.Vector(16.0591, -17.8355, 0)
	S051 = Part.LineSegment(P051, P052)
	P053 = App.Vector(15.6060, -14.0517, 0)
	S052 = Part.LineSegment(P052, P053)
	P054 = App.Vector(19.4164, -14.1068, 0)
	S053 = Part.LineSegment(P053, P054)
	P055 = App.Vector(18.1865, -10.5000, 0)
	S054 = Part.LineSegment(P054, P055)
	P056 = App.Vector(21.9251, -9.7617, 0)
	S055 = Part.LineSegment(P055, P056)
	P057 = App.Vector(19.9722, -6.4894, 0)
	S056 = Part.LineSegment(P056, P057)
	P058 = App.Vector(23.4755, -4.9899, 0)
	S057 = Part.LineSegment(P057, P058)
	P059 = App.Vector(20.8850, -2.1951, 0)
	S058 = Part.LineSegment(P058, P059)
	P060 = App.Vector(24.0000, -0.0000, 0)
	S059 = Part.LineSegment(P059, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047, S048, S049, S050, S051, S052, S053, S054, S055, S056, S057, S058, S059])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_ring_faceRingTeeth_Fa0():
	FC000 = ctr_face_ring_faceRingTeeth_Fa0_Ctr0()
	FC001 = ctr_face_ring_faceRingTeeth_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ring_faceRingTeeth():
	FA000 = face_ring_faceRingTeeth_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_ring_faceSection_Fa0_Ctr0():
	P000 = App.Vector(28.0000, 0.0000, 0)
	P001 = App.Vector(11.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(11.0000, -2.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(21.0000, -2.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(21.0000, -12.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(28.0000, -12.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(28.0000, 0.0000, 0)
	S005 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_ring_faceSection_Fa0():
	FC000 = ctr_face_ring_faceSection_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ring_faceSection():
	FA000 = face_ring_faceSection_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_ring_base():
	FIG = ring_faceRingBase()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_ring_base = fex_subpax_ring_base()

def fex_subpax_ring_teeth():
	FIG = ring_faceRingTeeth()
	VEX = FIG.extrude(App.Vector(0, 0, 12))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_ring_teeth = fex_subpax_ring_teeth()

def fvol_pax_ring():
	V000 = subpax_ring_base
	V001 = V000.fuse(subpax_ring_teeth)
	VFC = V001.removeSplitter()
	return VFC
pax_ring = fvol_pax_ring()


pax_ring.check()
#pax_ring.exportBrep(f"{outFileName}.brep")
#pax_ring.exportIges(f"{outFileName}.igs")
#pax_ring.exportStep(f"{outFileName}.stp")
pax_ring.exportStl(f"{outFileName}.stl")

