# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "rake_stopper"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_rake_stopper_faceCone_Fa0_Ctr0():
	P000 = App.Vector(40.0000, 0.0000, 0)
	P001 = App.Vector(40.0000, 20.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(25.0000, 200.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(23.0069, 199.8339, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(38.0000, 19.9168, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(38.0000, 0.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(40.0000, 0.0000, 0)
	S005 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rake_stopper_faceCone_Fa0():
	FC000 = ctr_face_rake_stopper_faceCone_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def rake_stopper_faceCone():
	FA000 = face_rake_stopper_faceCone_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_rake_stopper_faceBeam_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(0.0000, 180.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceBeam_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(13.0000, App.Vector(0.0000, 180.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_stopper_faceBeam_Fa0():
	FC000 = ctr_face_rake_stopper_faceBeam_Fa0_Ctr0()
	FC001 = ctr_face_rake_stopper_faceBeam_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def rake_stopper_faceBeam():
	FA000 = face_rake_stopper_faceBeam_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_rake_stopper_faceBeamHollow_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(13.0000, App.Vector(0.0000, 180.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_stopper_faceBeamHollow_Fa0():
	FC000 = ctr_face_rake_stopper_faceBeamHollow_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def rake_stopper_faceBeamHollow():
	FA000 = face_rake_stopper_faceBeamHollow_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(40.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(11.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(13.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(12.5570, 3.3646, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(11.2583, 6.5000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(9.1924, 9.1924, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(6.5000, 11.2583, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(3.3646, 12.5570, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(0.0000, 13.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr9():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-3.3646, 12.5570, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr10():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-6.5000, 11.2583, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr11():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-9.1924, 9.1924, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr12():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-11.2583, 6.5000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr13():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-12.5570, 3.3646, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr14():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-13.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr15():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-12.5570, -3.3646, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr16():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-11.2583, -6.5000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr17():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-9.1924, -9.1924, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr18():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-6.5000, -11.2583, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr19():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-3.3646, -12.5570, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr20():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-0.0000, -13.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr21():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(3.3646, -12.5570, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr22():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(6.5000, -11.2583, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr23():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(9.1924, -9.1924, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr24():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(11.2583, -6.5000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceDisc_Fa0_Ctr25():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(12.5570, -3.3646, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_stopper_faceDisc_Fa0():
	FC000 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr0()
	FC001 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr1()
	FC002 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr2()
	FC003 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr3()
	FC004 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr4()
	FC005 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr5()
	FC006 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr6()
	FC007 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr7()
	FC008 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr8()
	FC009 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr9()
	FC010 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr10()
	FC011 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr11()
	FC012 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr12()
	FC013 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr13()
	FC014 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr14()
	FC015 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr15()
	FC016 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr16()
	FC017 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr17()
	FC018 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr18()
	FC019 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr19()
	FC020 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr20()
	FC021 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr21()
	FC022 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr22()
	FC023 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr23()
	FC024 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr24()
	FC025 = ctr_face_rake_stopper_faceDisc_Fa0_Ctr25()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008, FC009, FC010, FC011, FC012, FC013, FC014, FC015, FC016, FC017, FC018, FC019, FC020, FC021, FC022, FC023, FC024, FC025])
	rOneFace.check()
	return rOneFace

def rake_stopper_faceDisc():
	FA000 = face_rake_stopper_faceDisc_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_rake_stopper_faceHand_Fa0_Ctr0():
	P000 = App.Vector(12.9904, 187.5000, 0)
	P001 = App.Vector(21.6506, 207.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(8.6603, 215.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-0.0000, 210.0000, 0)
	P004 = App.Vector(-8.6603, 215.0000, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(-21.6506, 207.5000, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-12.9904, 187.5000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(0.0000, 195.0000, 0)
	P008 = App.Vector(12.9904, 187.5000, 0)
	S005 = Part.Arc(P006, P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rake_stopper_faceHand_Fa0():
	FC000 = ctr_face_rake_stopper_faceHand_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def rake_stopper_faceHand():
	FA000 = face_rake_stopper_faceHand_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_rake_stopper_faceWing_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceWing_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(3.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_stopper_faceWing_Fa0():
	FC000 = ctr_face_rake_stopper_faceWing_Fa0_Ctr0()
	FC001 = ctr_face_rake_stopper_faceWing_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def rake_stopper_faceWing():
	FA000 = face_rake_stopper_faceWing_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_rake_stopper_faceWingHollow_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(3.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_stopper_faceWingHollow_Fa0():
	FC000 = ctr_face_rake_stopper_faceWingHollow_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def rake_stopper_faceWingHollow():
	FA000 = face_rake_stopper_faceWingHollow_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_rake_stopper_faceDoor_Fa0_Ctr0():
	P000 = App.Vector(-8.1528, 24.0000, 0)
	P001 = App.Vector(8.1528, 24.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(11.0963, 25.2916, 0)
	P003 = App.Vector(12.1390, 28.3322, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(8.6390, 70.3322, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(7.3612, 72.9435, 0)
	P006 = App.Vector(4.6528, 74.0000, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-4.6528, 74.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-7.3612, 72.9435, 0)
	P009 = App.Vector(-8.6390, 70.3322, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-12.1390, 28.3322, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-11.0963, 25.2916, 0)
	P012 = App.Vector(-8.1528, 24.0000, 0)
	S007 = Part.Arc(P010, P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rake_stopper_faceDoor_Fa0():
	FC000 = ctr_face_rake_stopper_faceDoor_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def rake_stopper_faceDoor():
	FA000 = face_rake_stopper_faceDoor_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_rake_stopper_faceStopperTop_Fa0_Ctr0():
	P000 = App.Vector(-40.0000, -60.5000, 0)
	P001 = App.Vector(-40.0000, 60.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-48.0000, 60.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-48.0000, -60.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-40.0000, -60.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rake_stopper_faceStopperTop_Fa0_Ctr1():
	P000 = App.Vector(-42.0000, -60.5000, 0)
	P001 = App.Vector(-42.0000, 60.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-46.0000, 60.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-46.0000, -60.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-42.0000, -60.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rake_stopper_faceStopperTop_Fa0():
	FC000 = ctr_face_rake_stopper_faceStopperTop_Fa0_Ctr0()
	FC001 = ctr_face_rake_stopper_faceStopperTop_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_rake_stopper_faceStopperTop_Fa1_Ctr0():
	P000 = App.Vector(160.0000, -60.5000, 0)
	P001 = App.Vector(160.0000, 60.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(152.0000, 60.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(152.0000, -60.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(160.0000, -60.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rake_stopper_faceStopperTop_Fa1_Ctr1():
	P000 = App.Vector(158.0000, -60.5000, 0)
	P001 = App.Vector(158.0000, 60.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(154.0000, 60.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(154.0000, -60.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(158.0000, -60.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rake_stopper_faceStopperTop_Fa1():
	FC000 = ctr_face_rake_stopper_faceStopperTop_Fa1_Ctr0()
	FC001 = ctr_face_rake_stopper_faceStopperTop_Fa1_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_rake_stopper_faceStopperTop_Fa2_Ctr0():
	P000 = App.Vector(0.0000, -60.5000, 0)
	P001 = App.Vector(156.0000, -60.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(156.0000, -52.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, -52.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, -60.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rake_stopper_faceStopperTop_Fa2_Ctr1():
	P000 = App.Vector(0.0000, -58.5000, 0)
	P001 = App.Vector(156.0000, -58.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(156.0000, -54.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, -54.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, -58.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rake_stopper_faceStopperTop_Fa2():
	FC000 = ctr_face_rake_stopper_faceStopperTop_Fa2_Ctr0()
	FC001 = ctr_face_rake_stopper_faceStopperTop_Fa2_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_rake_stopper_faceStopperTop_Fa3_Ctr0():
	P000 = App.Vector(0.0000, 52.5000, 0)
	P001 = App.Vector(156.0000, 52.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(156.0000, 60.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 60.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 52.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rake_stopper_faceStopperTop_Fa3_Ctr1():
	P000 = App.Vector(0.0000, 54.5000, 0)
	P001 = App.Vector(156.0000, 54.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(156.0000, 58.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 58.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 54.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rake_stopper_faceStopperTop_Fa3():
	FC000 = ctr_face_rake_stopper_faceStopperTop_Fa3_Ctr0()
	FC001 = ctr_face_rake_stopper_faceStopperTop_Fa3_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_rake_stopper_faceStopperTop_Fa4_Ctr0():
	P000 = App.Vector(0.0000, -48.0000, 0)
	P001 = App.Vector(156.0000, -48.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(156.0000, -40.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, -40.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, -48.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rake_stopper_faceStopperTop_Fa4_Ctr1():
	P000 = App.Vector(0.0000, -46.0000, 0)
	P001 = App.Vector(156.0000, -46.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(156.0000, -42.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, -42.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, -46.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rake_stopper_faceStopperTop_Fa4():
	FC000 = ctr_face_rake_stopper_faceStopperTop_Fa4_Ctr0()
	FC001 = ctr_face_rake_stopper_faceStopperTop_Fa4_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_rake_stopper_faceStopperTop_Fa5_Ctr0():
	P000 = App.Vector(0.0000, 40.0000, 0)
	P001 = App.Vector(156.0000, 40.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(156.0000, 48.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 48.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 40.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rake_stopper_faceStopperTop_Fa5_Ctr1():
	P000 = App.Vector(0.0000, 42.0000, 0)
	P001 = App.Vector(156.0000, 42.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(156.0000, 46.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 46.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 42.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rake_stopper_faceStopperTop_Fa5():
	FC000 = ctr_face_rake_stopper_faceStopperTop_Fa5_Ctr0()
	FC001 = ctr_face_rake_stopper_faceStopperTop_Fa5_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def rake_stopper_faceStopperTop():
	FA000 = face_rake_stopper_faceStopperTop_Fa0()
	FA001 = face_rake_stopper_faceStopperTop_Fa1()
	FA002 = face_rake_stopper_faceStopperTop_Fa2()
	FA003 = face_rake_stopper_faceStopperTop_Fa3()
	FA004 = face_rake_stopper_faceStopperTop_Fa4()
	FA005 = face_rake_stopper_faceStopperTop_Fa5()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005])
	rOneFig.check()
	return rOneFig

def ctr_face_rake_stopper_faceStopperSide_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(4.0000, App.Vector(-44.0000, 60.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceStopperSide_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.0000, App.Vector(-44.0000, 60.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_stopper_faceStopperSide_Fa0():
	FC000 = ctr_face_rake_stopper_faceStopperSide_Fa0_Ctr0()
	FC001 = ctr_face_rake_stopper_faceStopperSide_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_rake_stopper_faceStopperSide_Fa1_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(4.0000, App.Vector(156.0000, 199.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceStopperSide_Fa1_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.0000, App.Vector(156.0000, 199.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_stopper_faceStopperSide_Fa1():
	FC000 = ctr_face_rake_stopper_faceStopperSide_Fa1_Ctr0()
	FC001 = ctr_face_rake_stopper_faceStopperSide_Fa1_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def rake_stopper_faceStopperSide():
	FA000 = face_rake_stopper_faceStopperSide_Fa0()
	FA001 = face_rake_stopper_faceStopperSide_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_rake_stopper_faceStopperSideH_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.0000, App.Vector(-44.0000, 60.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_stopper_faceStopperSideH_Fa0():
	FC000 = ctr_face_rake_stopper_faceStopperSideH_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_rake_stopper_faceStopperSideH_Fa1_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.0000, App.Vector(156.0000, 199.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_stopper_faceStopperSideH_Fa1():
	FC000 = ctr_face_rake_stopper_faceStopperSideH_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def rake_stopper_faceStopperSideH():
	FA000 = face_rake_stopper_faceStopperSideH_Fa0()
	FA001 = face_rake_stopper_faceStopperSideH_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_rake_stopper_faceStopperFaceT_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(4.0000, App.Vector(-56.5000, 199.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceStopperFaceT_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.0000, App.Vector(-56.5000, 199.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_stopper_faceStopperFaceT_Fa0():
	FC000 = ctr_face_rake_stopper_faceStopperFaceT_Fa0_Ctr0()
	FC001 = ctr_face_rake_stopper_faceStopperFaceT_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_rake_stopper_faceStopperFaceT_Fa1_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(4.0000, App.Vector(56.5000, 199.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceStopperFaceT_Fa1_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.0000, App.Vector(56.5000, 199.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_stopper_faceStopperFaceT_Fa1():
	FC000 = ctr_face_rake_stopper_faceStopperFaceT_Fa1_Ctr0()
	FC001 = ctr_face_rake_stopper_faceStopperFaceT_Fa1_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def rake_stopper_faceStopperFaceT():
	FA000 = face_rake_stopper_faceStopperFaceT_Fa0()
	FA001 = face_rake_stopper_faceStopperFaceT_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_rake_stopper_faceStopperFaceTH_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.0000, App.Vector(-56.5000, 199.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_stopper_faceStopperFaceTH_Fa0():
	FC000 = ctr_face_rake_stopper_faceStopperFaceTH_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_rake_stopper_faceStopperFaceTH_Fa1_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.0000, App.Vector(56.5000, 199.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_stopper_faceStopperFaceTH_Fa1():
	FC000 = ctr_face_rake_stopper_faceStopperFaceTH_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def rake_stopper_faceStopperFaceTH():
	FA000 = face_rake_stopper_faceStopperFaceTH_Fa0()
	FA001 = face_rake_stopper_faceStopperFaceTH_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_rake_stopper_faceStopperFaceB_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(4.0000, App.Vector(-44.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceStopperFaceB_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.0000, App.Vector(-44.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_stopper_faceStopperFaceB_Fa0():
	FC000 = ctr_face_rake_stopper_faceStopperFaceB_Fa0_Ctr0()
	FC001 = ctr_face_rake_stopper_faceStopperFaceB_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_rake_stopper_faceStopperFaceB_Fa1_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(4.0000, App.Vector(44.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceStopperFaceB_Fa1_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.0000, App.Vector(44.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_stopper_faceStopperFaceB_Fa1():
	FC000 = ctr_face_rake_stopper_faceStopperFaceB_Fa1_Ctr0()
	FC001 = ctr_face_rake_stopper_faceStopperFaceB_Fa1_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def rake_stopper_faceStopperFaceB():
	FA000 = face_rake_stopper_faceStopperFaceB_Fa0()
	FA001 = face_rake_stopper_faceStopperFaceB_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_rake_stopper_faceStopperFaceBH_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.0000, App.Vector(-44.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_stopper_faceStopperFaceBH_Fa0():
	FC000 = ctr_face_rake_stopper_faceStopperFaceBH_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_rake_stopper_faceStopperFaceBH_Fa1_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.0000, App.Vector(44.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_stopper_faceStopperFaceBH_Fa1():
	FC000 = ctr_face_rake_stopper_faceStopperFaceBH_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def rake_stopper_faceStopperFaceBH():
	FA000 = face_rake_stopper_faceStopperFaceBH_Fa0()
	FA001 = face_rake_stopper_faceStopperFaceBH_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_rake_stopper_faceLowStopperHolder_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(-21.0000, 58.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceLowStopperHolder_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(8.0000, App.Vector(-21.0000, 58.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_stopper_faceLowStopperHolder_Fa0():
	FC000 = ctr_face_rake_stopper_faceLowStopperHolder_Fa0_Ctr0()
	FC001 = ctr_face_rake_stopper_faceLowStopperHolder_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_rake_stopper_faceLowStopperHolder_Fa1_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(21.0000, 58.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceLowStopperHolder_Fa1_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(8.0000, App.Vector(21.0000, 58.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_stopper_faceLowStopperHolder_Fa1():
	FC000 = ctr_face_rake_stopper_faceLowStopperHolder_Fa1_Ctr0()
	FC001 = ctr_face_rake_stopper_faceLowStopperHolder_Fa1_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def rake_stopper_faceLowStopperHolder():
	FA000 = face_rake_stopper_faceLowStopperHolder_Fa0()
	FA001 = face_rake_stopper_faceLowStopperHolder_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_rake_stopper_faceHi1StopperHolder_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(0.0000, 20.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceHi1StopperHolder_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(3.0000, App.Vector(0.0000, 20.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_stopper_faceHi1StopperHolder_Fa0():
	FC000 = ctr_face_rake_stopper_faceHi1StopperHolder_Fa0_Ctr0()
	FC001 = ctr_face_rake_stopper_faceHi1StopperHolder_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def rake_stopper_faceHi1StopperHolder():
	FA000 = face_rake_stopper_faceHi1StopperHolder_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_rake_stopper_faceHi2StopperHolder_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(0.0000, -56.5000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceHi2StopperHolder_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(3.0000, App.Vector(0.0000, -56.5000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_stopper_faceHi2StopperHolder_Fa0():
	FC000 = ctr_face_rake_stopper_faceHi2StopperHolder_Fa0_Ctr0()
	FC001 = ctr_face_rake_stopper_faceHi2StopperHolder_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_rake_stopper_faceHi2StopperHolder_Fa1_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(0.0000, 56.5000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_stopper_faceHi2StopperHolder_Fa1_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(3.0000, App.Vector(0.0000, 56.5000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_stopper_faceHi2StopperHolder_Fa1():
	FC000 = ctr_face_rake_stopper_faceHi2StopperHolder_Fa1_Ctr0()
	FC001 = ctr_face_rake_stopper_faceHi2StopperHolder_Fa1_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def rake_stopper_faceHi2StopperHolder():
	FA000 = face_rake_stopper_faceHi2StopperHolder_Fa0()
	FA001 = face_rake_stopper_faceHi2StopperHolder_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_rake_faceCone_Fa0_Ctr0():
	P000 = App.Vector(40.0000, 0.0000, 0)
	P001 = App.Vector(40.0000, 20.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(25.0000, 200.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(23.0069, 199.8339, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(38.0000, 19.9168, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(38.0000, 0.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(40.0000, 0.0000, 0)
	S005 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rake_faceCone_Fa0():
	FC000 = ctr_face_rake_faceCone_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def rake_faceCone():
	FA000 = face_rake_faceCone_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_rake_faceConeHollow_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 165.0000, 0)
	P001 = App.Vector(25.9097, 165.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(38.0000, 19.9168, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(38.0000, 6.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 6.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(0.0000, 165.0000, 0)
	S004 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rake_faceConeHollow_Fa0():
	FC000 = ctr_face_rake_faceConeHollow_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def rake_faceConeHollow():
	FA000 = face_rake_faceConeHollow_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_rake_faceBeam_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(0.0000, 180.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceBeam_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(13.0000, App.Vector(0.0000, 180.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_faceBeam_Fa0():
	FC000 = ctr_face_rake_faceBeam_Fa0_Ctr0()
	FC001 = ctr_face_rake_faceBeam_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def rake_faceBeam():
	FA000 = face_rake_faceBeam_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_rake_faceBeamHollow_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(13.0000, App.Vector(0.0000, 180.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_faceBeamHollow_Fa0():
	FC000 = ctr_face_rake_faceBeamHollow_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def rake_faceBeamHollow():
	FA000 = face_rake_faceBeamHollow_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_rake_faceDisc_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(40.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(11.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(13.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(12.5570, 3.3646, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(11.2583, 6.5000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(9.1924, 9.1924, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(6.5000, 11.2583, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(3.3646, 12.5570, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(0.0000, 13.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr9():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-3.3646, 12.5570, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr10():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-6.5000, 11.2583, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr11():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-9.1924, 9.1924, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr12():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-11.2583, 6.5000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr13():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-12.5570, 3.3646, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr14():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-13.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr15():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-12.5570, -3.3646, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr16():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-11.2583, -6.5000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr17():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-9.1924, -9.1924, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr18():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-6.5000, -11.2583, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr19():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-3.3646, -12.5570, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr20():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-0.0000, -13.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr21():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(3.3646, -12.5570, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr22():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(6.5000, -11.2583, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr23():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(9.1924, -9.1924, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr24():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(11.2583, -6.5000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceDisc_Fa0_Ctr25():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(12.5570, -3.3646, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_faceDisc_Fa0():
	FC000 = ctr_face_rake_faceDisc_Fa0_Ctr0()
	FC001 = ctr_face_rake_faceDisc_Fa0_Ctr1()
	FC002 = ctr_face_rake_faceDisc_Fa0_Ctr2()
	FC003 = ctr_face_rake_faceDisc_Fa0_Ctr3()
	FC004 = ctr_face_rake_faceDisc_Fa0_Ctr4()
	FC005 = ctr_face_rake_faceDisc_Fa0_Ctr5()
	FC006 = ctr_face_rake_faceDisc_Fa0_Ctr6()
	FC007 = ctr_face_rake_faceDisc_Fa0_Ctr7()
	FC008 = ctr_face_rake_faceDisc_Fa0_Ctr8()
	FC009 = ctr_face_rake_faceDisc_Fa0_Ctr9()
	FC010 = ctr_face_rake_faceDisc_Fa0_Ctr10()
	FC011 = ctr_face_rake_faceDisc_Fa0_Ctr11()
	FC012 = ctr_face_rake_faceDisc_Fa0_Ctr12()
	FC013 = ctr_face_rake_faceDisc_Fa0_Ctr13()
	FC014 = ctr_face_rake_faceDisc_Fa0_Ctr14()
	FC015 = ctr_face_rake_faceDisc_Fa0_Ctr15()
	FC016 = ctr_face_rake_faceDisc_Fa0_Ctr16()
	FC017 = ctr_face_rake_faceDisc_Fa0_Ctr17()
	FC018 = ctr_face_rake_faceDisc_Fa0_Ctr18()
	FC019 = ctr_face_rake_faceDisc_Fa0_Ctr19()
	FC020 = ctr_face_rake_faceDisc_Fa0_Ctr20()
	FC021 = ctr_face_rake_faceDisc_Fa0_Ctr21()
	FC022 = ctr_face_rake_faceDisc_Fa0_Ctr22()
	FC023 = ctr_face_rake_faceDisc_Fa0_Ctr23()
	FC024 = ctr_face_rake_faceDisc_Fa0_Ctr24()
	FC025 = ctr_face_rake_faceDisc_Fa0_Ctr25()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008, FC009, FC010, FC011, FC012, FC013, FC014, FC015, FC016, FC017, FC018, FC019, FC020, FC021, FC022, FC023, FC024, FC025])
	rOneFace.check()
	return rOneFace

def rake_faceDisc():
	FA000 = face_rake_faceDisc_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_rake_faceHand_Fa0_Ctr0():
	P000 = App.Vector(12.9904, 187.5000, 0)
	P001 = App.Vector(21.6506, 207.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(8.6603, 215.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-0.0000, 210.0000, 0)
	P004 = App.Vector(-8.6603, 215.0000, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(-21.6506, 207.5000, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-12.9904, 187.5000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(0.0000, 195.0000, 0)
	P008 = App.Vector(12.9904, 187.5000, 0)
	S005 = Part.Arc(P006, P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rake_faceHand_Fa0():
	FC000 = ctr_face_rake_faceHand_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def rake_faceHand():
	FA000 = face_rake_faceHand_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_rake_faceWing_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rake_faceWing_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(3.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_faceWing_Fa0():
	FC000 = ctr_face_rake_faceWing_Fa0_Ctr0()
	FC001 = ctr_face_rake_faceWing_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def rake_faceWing():
	FA000 = face_rake_faceWing_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_rake_faceWingHollow_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(3.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rake_faceWingHollow_Fa0():
	FC000 = ctr_face_rake_faceWingHollow_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def rake_faceWingHollow():
	FA000 = face_rake_faceWingHollow_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_rake_faceDoor_Fa0_Ctr0():
	P000 = App.Vector(-8.1528, 24.0000, 0)
	P001 = App.Vector(8.1528, 24.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(11.0963, 25.2916, 0)
	P003 = App.Vector(12.1390, 28.3322, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(8.6390, 70.3322, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(7.3612, 72.9435, 0)
	P006 = App.Vector(4.6528, 74.0000, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-4.6528, 74.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-7.3612, 72.9435, 0)
	P009 = App.Vector(-8.6390, 70.3322, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-12.1390, 28.3322, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-11.0963, 25.2916, 0)
	P012 = App.Vector(-8.1528, 24.0000, 0)
	S007 = Part.Arc(P010, P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rake_faceDoor_Fa0():
	FC000 = ctr_face_rake_faceDoor_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def rake_faceDoor():
	FA000 = face_rake_faceDoor_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_rake_cone():
	FIG = rake_faceCone()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_rake_cone = fex_subpax_rake_cone()

def fex_subpax_rake_coneHollow():
	FIG = rake_faceConeHollow()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_rake_coneHollow = fex_subpax_rake_coneHollow()

def fex_subpax_rake_beam():
	FIG = rake_faceBeam()
	VEX = FIG.extrude(App.Vector(0, 0, 293))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 146.5000, 0.0000))
	return VFP
subpax_rake_beam = fex_subpax_rake_beam()

def fex_subpax_rake_beamHollow():
	FIG = rake_faceBeamHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 293))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 146.5000, 0.0000))
	return VFP
subpax_rake_beamHollow = fex_subpax_rake_beamHollow()

def fex_subpax_rake_disc():
	FIG = rake_faceDisc()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 4.0000))
	return VFP
subpax_rake_disc = fex_subpax_rake_disc()

def fex_subpax_rake_wing_right():
	FIG = rake_faceWing()
	VEX = FIG.extrude(App.Vector(0, 0, 181.5835800096777))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -35.6764)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 33.9735, 22.4114))
	return VFP
subpax_rake_wing_right = fex_subpax_rake_wing_right()

def fex_subpax_rake_wing_left():
	FIG = rake_faceWing()
	VEX = FIG.extrude(App.Vector(0, 0, 181.5835800096777))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 35.6764)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, -33.9735, 22.4114))
	return VFP
subpax_rake_wing_left = fex_subpax_rake_wing_left()

def fex_subpax_rake_wing_hollow_right():
	FIG = rake_faceWingHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 181.5835800096777))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -35.6764)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 33.9735, 22.4114))
	return VFP
subpax_rake_wing_hollow_right = fex_subpax_rake_wing_hollow_right()

def fex_subpax_rake_wing_hollow_left():
	FIG = rake_faceWingHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 181.5835800096777))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 35.6764)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, -33.9735, 22.4114))
	return VFP
subpax_rake_wing_hollow_left = fex_subpax_rake_wing_hollow_left()

def fex_subpax_rake_door():
	FIG = rake_faceDoor()
	VEX = FIG.extrude(App.Vector(0, 0, 80))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_rake_door = fex_subpax_rake_door()

def fex_subpax_rake_hand_0():
	FIG = rake_faceHand()
	VEX = FIG.extrude(App.Vector(0, 0, 13))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 146.5000, 0.0000))
	return VFP
subpax_rake_hand_0 = fex_subpax_rake_hand_0()

def fex_subpax_rake_hand_1():
	FIG = rake_faceHand()
	VEX = FIG.extrude(App.Vector(0, 0, 13))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 73.5000, 0.0000))
	return VFP
subpax_rake_hand_1 = fex_subpax_rake_hand_1()

def fex_subpax_rake_hand_2():
	FIG = rake_faceHand()
	VEX = FIG.extrude(App.Vector(0, 0, 13))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, -60.5000, 0.0000))
	return VFP
subpax_rake_hand_2 = fex_subpax_rake_hand_2()

def fex_subpax_rake_hand_3():
	FIG = rake_faceHand()
	VEX = FIG.extrude(App.Vector(0, 0, 13))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, -133.5000, 0.0000))
	return VFP
subpax_rake_hand_3 = fex_subpax_rake_hand_3()

ipax_rake_plus = subpax_rake_cone.fuse([subpax_rake_beam, subpax_rake_disc, subpax_rake_hand_0, subpax_rake_hand_1, subpax_rake_hand_2, subpax_rake_hand_3, subpax_rake_wing_right, subpax_rake_wing_left])
ipax_rake_hollow = subpax_rake_coneHollow.fuse([subpax_rake_beamHollow, subpax_rake_wing_hollow_right, subpax_rake_wing_hollow_left, subpax_rake_door])
pax_rake = ipax_rake_plus.cut([ipax_rake_hollow])
def finh_inpax_rake_stopper_rake():
	IVR1 = pax_rake.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	IVR2 = IVR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	IVR3 = IVR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	IVF = IVR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return IVF
inpax_rake_stopper_rake = finh_inpax_rake_stopper_rake()

def finh_inpax_rake_stopper_coneHollow():
	IVR1 = subpax_rake_coneHollow.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	IVR2 = IVR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	IVR3 = IVR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	IVF = IVR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return IVF
inpax_rake_stopper_coneHollow = finh_inpax_rake_stopper_coneHollow()

def finh_inpax_rake_stopper_beamHollow():
	IVR1 = subpax_rake_beamHollow.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	IVR2 = IVR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	IVR3 = IVR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	IVF = IVR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return IVF
inpax_rake_stopper_beamHollow = finh_inpax_rake_stopper_beamHollow()

def fex_subpax_rake_stopper_stpSide():
	FIG = rake_stopper_faceStopperSide()
	VEX = FIG.extrude(App.Vector(0, 0, 121))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 60.5000, 0.0000))
	return VFP
subpax_rake_stopper_stpSide = fex_subpax_rake_stopper_stpSide()

def fex_subpax_rake_stopper_stpSideH():
	FIG = rake_stopper_faceStopperSideH()
	VEX = FIG.extrude(App.Vector(0, 0, 121))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 60.5000, 0.0000))
	return VFP
subpax_rake_stopper_stpSideH = fex_subpax_rake_stopper_stpSideH()

def fex_subpax_rake_stopper_stpFaceT():
	FIG = rake_stopper_faceStopperFaceT()
	VEX = FIG.extrude(App.Vector(0, 0, 156))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_rake_stopper_stpFaceT = fex_subpax_rake_stopper_stpFaceT()

def fex_subpax_rake_stopper_stpFaceTH():
	FIG = rake_stopper_faceStopperFaceTH()
	VEX = FIG.extrude(App.Vector(0, 0, 156))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_rake_stopper_stpFaceTH = fex_subpax_rake_stopper_stpFaceTH()

def fex_subpax_rake_stopper_stpFaceB():
	FIG = rake_stopper_faceStopperFaceB()
	VEX = FIG.extrude(App.Vector(0, 0, 237.43841306747314))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 41.0724)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 20.0000))
	return VFP
subpax_rake_stopper_stpFaceB = fex_subpax_rake_stopper_stpFaceB()

def fex_subpax_rake_stopper_stpFaceBH():
	FIG = rake_stopper_faceStopperFaceBH()
	VEX = FIG.extrude(App.Vector(0, 0, 237.43841306747314))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 41.0724)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 20.0000))
	return VFP
subpax_rake_stopper_stpFaceBH = fex_subpax_rake_stopper_stpFaceBH()

def fex_subpax_rake_stopper_lowSH():
	FIG = rake_stopper_faceLowStopperHolder()
	VEX = FIG.extrude(App.Vector(0, 0, 50))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_rake_stopper_lowSH = fex_subpax_rake_stopper_lowSH()

def fex_subpax_rake_stopper_Hi1SH1():
	FIG = rake_stopper_faceHi1StopperHolder()
	VEX = FIG.extrude(App.Vector(0, 0, 50))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_rake_stopper_Hi1SH1 = fex_subpax_rake_stopper_Hi1SH1()

def fex_subpax_rake_stopper_Hi1SH2():
	FIG = rake_stopper_faceHi1StopperHolder()
	VEX = FIG.extrude(App.Vector(0, 0, 50))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 180.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_rake_stopper_Hi1SH2 = fex_subpax_rake_stopper_Hi1SH2()

def fex_subpax_rake_stopper_Hi2SH():
	FIG = rake_stopper_faceHi2StopperHolder()
	VEX = FIG.extrude(App.Vector(0, 0, 25))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 180.0000))
	return VFP
subpax_rake_stopper_Hi2SH = fex_subpax_rake_stopper_Hi2SH()

ipax_rake_stopper_plus = subpax_rake_stopper_stpSide.fuse([subpax_rake_stopper_stpFaceT, subpax_rake_stopper_stpFaceB, subpax_rake_stopper_lowSH, subpax_rake_stopper_Hi1SH1, subpax_rake_stopper_Hi1SH2, subpax_rake_stopper_Hi2SH])
ipax_rake_stopper_hollow = inpax_rake_stopper_coneHollow.fuse([inpax_rake_stopper_beamHollow, subpax_rake_stopper_stpSideH, subpax_rake_stopper_stpFaceTH, subpax_rake_stopper_stpFaceBH])
ipax_rake_stopper_stopper = ipax_rake_stopper_plus.cut([ipax_rake_stopper_hollow])
pax_rake_stopper = inpax_rake_stopper_rake.fuse([ipax_rake_stopper_stopper])

pax_rake_stopper.check()
#pax_rake_stopper.exportBrep(f"{outFileName}.brep")
#pax_rake_stopper.exportIges(f"{outFileName}.igs")
#pax_rake_stopper.exportStep(f"{outFileName}.stp")
pax_rake_stopper.exportStl(f"{outFileName}.stl")

