# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "trapeze"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_trapeze_faceFrame_Fa0_Ctr0():
	P000 = App.Vector(23.0000, 40.0000, 0)
	P001 = App.Vector(-23.0000, 40.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-24.4142, 39.4142, 0)
	P003 = App.Vector(-25.0000, 38.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-25.0000, -38.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-24.4142, -39.4142, 0)
	P006 = App.Vector(-23.0000, -40.0000, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(23.0000, -40.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(24.4142, -39.4142, 0)
	P009 = App.Vector(25.0000, -38.0000, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(25.0000, 38.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(24.4142, 39.4142, 0)
	P012 = App.Vector(23.0000, 40.0000, 0)
	S007 = Part.Arc(P010, P011, P012)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_trapeze_faceFrame_Fa0_Ctr1():
	P000 = App.Vector(14.0000, 35.0000, 0)
	P001 = App.Vector(-14.0000, 35.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-18.2426, 33.2426, 0)
	P003 = App.Vector(-20.0000, 29.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-20.0000, -29.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-18.2426, -33.2426, 0)
	P006 = App.Vector(-14.0000, -35.0000, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(14.0000, -35.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(18.2426, -33.2426, 0)
	P009 = App.Vector(20.0000, -29.0000, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(20.0000, 29.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(18.2426, 33.2426, 0)
	P012 = App.Vector(14.0000, 35.0000, 0)
	S007 = Part.Arc(P010, P011, P012)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_trapeze_faceFrame_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(23.0000, -30.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_faceFrame_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-23.0000, -30.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_faceFrame_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(23.0000, -20.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_faceFrame_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-23.0000, -20.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_faceFrame_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(23.0000, -10.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_faceFrame_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-23.0000, -10.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_faceFrame_Fa0_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(23.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_faceFrame_Fa0_Ctr9():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-23.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_faceFrame_Fa0_Ctr10():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(23.0000, 10.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_faceFrame_Fa0_Ctr11():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-23.0000, 10.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_faceFrame_Fa0_Ctr12():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(23.0000, 20.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_faceFrame_Fa0_Ctr13():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-23.0000, 20.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_faceFrame_Fa0_Ctr14():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(23.0000, 30.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_faceFrame_Fa0_Ctr15():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-23.0000, 30.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_faceFrame_Fa0_Ctr16():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.0000, 38.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_faceFrame_Fa0_Ctr17():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.0000, -38.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_faceFrame_Fa0_Ctr18():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-5.0000, 38.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_faceFrame_Fa0_Ctr19():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-5.0000, -38.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_faceFrame_Fa0_Ctr20():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(5.0000, 38.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_faceFrame_Fa0_Ctr21():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(5.0000, -38.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_faceFrame_Fa0_Ctr22():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.0000, 38.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_faceFrame_Fa0_Ctr23():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.0000, -38.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_trapeze_faceFrame_Fa0():
	FC000 = ctr_face_trapeze_faceFrame_Fa0_Ctr0()
	FC001 = ctr_face_trapeze_faceFrame_Fa0_Ctr1()
	FC002 = ctr_face_trapeze_faceFrame_Fa0_Ctr2()
	FC003 = ctr_face_trapeze_faceFrame_Fa0_Ctr3()
	FC004 = ctr_face_trapeze_faceFrame_Fa0_Ctr4()
	FC005 = ctr_face_trapeze_faceFrame_Fa0_Ctr5()
	FC006 = ctr_face_trapeze_faceFrame_Fa0_Ctr6()
	FC007 = ctr_face_trapeze_faceFrame_Fa0_Ctr7()
	FC008 = ctr_face_trapeze_faceFrame_Fa0_Ctr8()
	FC009 = ctr_face_trapeze_faceFrame_Fa0_Ctr9()
	FC010 = ctr_face_trapeze_faceFrame_Fa0_Ctr10()
	FC011 = ctr_face_trapeze_faceFrame_Fa0_Ctr11()
	FC012 = ctr_face_trapeze_faceFrame_Fa0_Ctr12()
	FC013 = ctr_face_trapeze_faceFrame_Fa0_Ctr13()
	FC014 = ctr_face_trapeze_faceFrame_Fa0_Ctr14()
	FC015 = ctr_face_trapeze_faceFrame_Fa0_Ctr15()
	FC016 = ctr_face_trapeze_faceFrame_Fa0_Ctr16()
	FC017 = ctr_face_trapeze_faceFrame_Fa0_Ctr17()
	FC018 = ctr_face_trapeze_faceFrame_Fa0_Ctr18()
	FC019 = ctr_face_trapeze_faceFrame_Fa0_Ctr19()
	FC020 = ctr_face_trapeze_faceFrame_Fa0_Ctr20()
	FC021 = ctr_face_trapeze_faceFrame_Fa0_Ctr21()
	FC022 = ctr_face_trapeze_faceFrame_Fa0_Ctr22()
	FC023 = ctr_face_trapeze_faceFrame_Fa0_Ctr23()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008, FC009, FC010, FC011, FC012, FC013, FC014, FC015, FC016, FC017, FC018, FC019, FC020, FC021, FC022, FC023])
	rOneFace.check()
	return rOneFace

def trapeze_faceFrame():
	FA000 = face_trapeze_faceFrame_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_trapeze_facePlate_Fa0_Ctr0():
	P000 = App.Vector(13.0000, 20.0000, 0)
	P001 = App.Vector(-13.0000, 20.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-14.4142, 19.4142, 0)
	P003 = App.Vector(-15.0000, 18.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-15.0000, -18.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-14.4142, -19.4142, 0)
	P006 = App.Vector(-13.0000, -20.0000, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(13.0000, -20.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(14.4142, -19.4142, 0)
	P009 = App.Vector(15.0000, -18.0000, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(15.0000, 18.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(14.4142, 19.4142, 0)
	P012 = App.Vector(13.0000, 20.0000, 0)
	S007 = Part.Arc(P010, P011, P012)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_trapeze_facePlate_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(12.0000, -6.6667, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_facePlate_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-12.0000, -6.6667, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_facePlate_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(12.0000, 6.6667, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_facePlate_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-12.0000, 6.6667, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_facePlate_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-5.0000, 17.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_facePlate_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-5.0000, -17.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_facePlate_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(5.0000, 17.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_trapeze_facePlate_Fa0_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(5.0000, -17.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_trapeze_facePlate_Fa0():
	FC000 = ctr_face_trapeze_facePlate_Fa0_Ctr0()
	FC001 = ctr_face_trapeze_facePlate_Fa0_Ctr1()
	FC002 = ctr_face_trapeze_facePlate_Fa0_Ctr2()
	FC003 = ctr_face_trapeze_facePlate_Fa0_Ctr3()
	FC004 = ctr_face_trapeze_facePlate_Fa0_Ctr4()
	FC005 = ctr_face_trapeze_facePlate_Fa0_Ctr5()
	FC006 = ctr_face_trapeze_facePlate_Fa0_Ctr6()
	FC007 = ctr_face_trapeze_facePlate_Fa0_Ctr7()
	FC008 = ctr_face_trapeze_facePlate_Fa0_Ctr8()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008])
	rOneFace.check()
	return rOneFace

def trapeze_facePlate():
	FA000 = face_trapeze_facePlate_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_trapeze_faceRod_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.5000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_trapeze_faceRod_Fa0():
	FC000 = ctr_face_trapeze_faceRod_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def trapeze_faceRod():
	FA000 = face_trapeze_faceRod_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_trapeze_faceRodHollow_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_trapeze_faceRodHollow_Fa0():
	FC000 = ctr_face_trapeze_faceRodHollow_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def trapeze_faceRodHollow():
	FA000 = face_trapeze_faceRodHollow_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_trapeze_faceCutRod_Fa0_Ctr0():
	P000 = App.Vector(133.5650, 133.5650, 0)
	P001 = App.Vector(-133.5650, 133.5650, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-133.5650, -133.5650, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(133.5650, -133.5650, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(133.5650, 133.5650, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_trapeze_faceCutRod_Fa0():
	FC000 = ctr_face_trapeze_faceCutRod_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def trapeze_faceCutRod():
	FA000 = face_trapeze_faceCutRod_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_trapeze_frame():
	FIG = trapeze_faceFrame()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(0, 0, 24))
	return VFP
subpax_trapeze_frame = fex_subpax_trapeze_frame()

def fex_subpax_trapeze_plate():
	FIG = trapeze_facePlate()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(0, 0, 0))
	return VFP
subpax_trapeze_plate = fex_subpax_trapeze_plate()

def fex_subpax_trapeze_rod1():
	FIG = trapeze_faceRod()
	VEX = FIG.extrude(App.Vector(0, 0, 60.00082232516408))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 45.46583987463105)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 63.434948822922)
	VFP = VR3.translate(App.Vector(11.199987307122505, 12.985761051871918, -1.564162178201257))
	return VFP
subpax_trapeze_rod1 = fex_subpax_trapeze_rod1()

def fex_subpax_trapeze_rod2():
	FIG = trapeze_faceRod()
	VEX = FIG.extrude(App.Vector(0, 0, 60.00082232516408))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 45.46583987463105)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 116.56505117707799)
	VFP = VR3.translate(App.Vector(-11.199987307122505, 12.985761051871918, -1.564162178201257))
	return VFP
subpax_trapeze_rod2 = fex_subpax_trapeze_rod2()

def fex_subpax_trapeze_rod3():
	FIG = trapeze_faceRod()
	VEX = FIG.extrude(App.Vector(0, 0, 60.00082232516408))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 45.46583987463105)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 243.434948822922)
	VFP = VR3.translate(App.Vector(-11.199987307122505, -12.985761051871918, -1.564162178201257))
	return VFP
subpax_trapeze_rod3 = fex_subpax_trapeze_rod3()

def fex_subpax_trapeze_rod4():
	FIG = trapeze_faceRod()
	VEX = FIG.extrude(App.Vector(0, 0, 60.00082232516408))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 45.46583987463105)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -63.434948822922)
	VFP = VR3.translate(App.Vector(11.199987307122505, -12.985761051871918, -1.564162178201257))
	return VFP
subpax_trapeze_rod4 = fex_subpax_trapeze_rod4()

def fex_subpax_trapeze_rodH1():
	FIG = trapeze_faceRodHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 60.00082232516408))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 45.46583987463105)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 63.434948822922)
	VFP = VR3.translate(App.Vector(11.199987307122505, 12.985761051871918, -1.564162178201257))
	return VFP
subpax_trapeze_rodH1 = fex_subpax_trapeze_rodH1()

def fex_subpax_trapeze_rodH2():
	FIG = trapeze_faceRodHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 60.00082232516408))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 45.46583987463105)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 116.56505117707799)
	VFP = VR3.translate(App.Vector(-11.199987307122505, 12.985761051871918, -1.564162178201257))
	return VFP
subpax_trapeze_rodH2 = fex_subpax_trapeze_rodH2()

def fex_subpax_trapeze_rodH3():
	FIG = trapeze_faceRodHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 60.00082232516408))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 45.46583987463105)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 243.434948822922)
	VFP = VR3.translate(App.Vector(-11.199987307122505, -12.985761051871918, -1.564162178201257))
	return VFP
subpax_trapeze_rodH3 = fex_subpax_trapeze_rodH3()

def fex_subpax_trapeze_rodH4():
	FIG = trapeze_faceRodHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 60.00082232516408))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 45.46583987463105)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -63.434948822922)
	VFP = VR3.translate(App.Vector(11.199987307122505, -12.985761051871918, -1.564162178201257))
	return VFP
subpax_trapeze_rodH4 = fex_subpax_trapeze_rodH4()

def fex_subpax_trapeze_cut1():
	FIG = trapeze_faceCutRod()
	VEX = FIG.extrude(App.Vector(0, 0, 133.56498450336534))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(0, 0, -133.56498450336534))
	return VFP
subpax_trapeze_cut1 = fex_subpax_trapeze_cut1()

def fex_subpax_trapeze_cut2():
	FIG = trapeze_faceCutRod()
	VEX = FIG.extrude(App.Vector(0, 0, 133.56498450336534))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(0, 0, 25))
	return VFP
subpax_trapeze_cut2 = fex_subpax_trapeze_cut2()

ipax_trapeze_rawRod = subpax_trapeze_rod1.fuse([subpax_trapeze_rod2, subpax_trapeze_rod3, subpax_trapeze_rod4])
ipax_trapeze_rodHollow = subpax_trapeze_rodH1.fuse([subpax_trapeze_rodH2, subpax_trapeze_rodH3, subpax_trapeze_rodH4])
ipax_trapeze_halfRods = ipax_trapeze_rawRod.cut([subpax_trapeze_cut1])
ipax_trapeze_rods = ipax_trapeze_halfRods.cut([subpax_trapeze_cut2])
ipax_trapeze_plus = subpax_trapeze_frame.fuse([subpax_trapeze_plate, ipax_trapeze_rods])
pax_trapeze = ipax_trapeze_plus.cut([ipax_trapeze_rodHollow])

pax_trapeze.check()
#pax_trapeze.exportBrep(f"{outFileName}.brep")
#pax_trapeze.exportIges(f"{outFileName}.igs")
#pax_trapeze.exportStep(f"{outFileName}.stp")
pax_trapeze.exportStl(f"{outFileName}.stl")

