# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "haxis_guidance"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_haxis_guidance_faceProfile_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 11.0000, 0)
	P001 = App.Vector(2.4835, 10.7276, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(3.2337, 10.7956, 0)
	P003 = App.Vector(3.8402, 11.2426, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(8.7655, 17.5467, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(9.4673, 17.6328, 0)
	P006 = App.Vector(9.5535, 16.9310, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(4.6282, 10.6269, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(4.8695, 8.6618, 0)
	P009 = App.Vector(6.8346, 8.9031, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(11.7599, 15.2072, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(12.4617, 15.2933, 0)
	P012 = App.Vector(12.5479, 14.5915, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(7.2532, 7.8146, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(7.4945, 5.8495, 0)
	P015 = App.Vector(9.4596, 6.0907, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(8.7504, 6.6448, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(8.0486, 6.5587, 0)
	P018 = App.Vector(7.9624, 7.2605, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(13.2571, 14.0374, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(13.0158, 16.0025, 0)
	P021 = App.Vector(11.0507, 15.7613, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(6.1254, 9.4572, 0)
	S014 = Part.LineSegment(P021, P022)
	P023 = App.Vector(5.4236, 9.3710, 0)
	P024 = App.Vector(5.3374, 10.0728, 0)
	S015 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(10.2627, 16.3769, 0)
	S016 = Part.LineSegment(P024, P025)
	P026 = App.Vector(10.0214, 18.3421, 0)
	P027 = App.Vector(8.0562, 18.1008, 0)
	S017 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(3.1310, 11.7967, 0)
	S018 = Part.LineSegment(P027, P028)
	P029 = App.Vector(2.5319, 11.6485, 0)
	P030 = App.Vector(2.2452, 12.1950, 0)
	S019 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(3.1309, 17.0058, 0)
	S020 = Part.LineSegment(P030, P031)
	P032 = App.Vector(5.8169, 20.5750, 0)
	P033 = App.Vector(10.2839, 20.5728, 0)
	S021 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(19.9186, 11.5000, 0)
	P035 = App.Vector(22.9585, -1.3803, 0)
	S022 = Part.Arc(P033, P034, P035)
	P036 = App.Vector(20.7269, -5.2499, 0)
	P037 = App.Vector(16.2929, -5.7915, 0)
	S023 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(11.6838, -4.1531, 0)
	S024 = Part.LineSegment(P037, P038)
	P039 = App.Vector(11.3538, -3.6316, 0)
	P040 = App.Vector(11.7817, -3.1869, 0)
	S025 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(19.7038, -2.0735, 0)
	S026 = Part.LineSegment(P040, P041)
	P042 = App.Vector(20.8954, -0.4923, 0)
	P043 = App.Vector(19.3142, 0.6993, 0)
	S027 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(11.3920, -0.4141, 0)
	S028 = Part.LineSegment(P043, P044)
	P045 = App.Vector(10.8273, 0.0114, 0)
	P046 = App.Vector(11.2528, 0.5762, 0)
	S029 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(19.1750, 1.6895, 0)
	S030 = Part.LineSegment(P046, P047)
	P048 = App.Vector(20.3665, 3.2708, 0)
	P049 = App.Vector(18.7853, 4.4623, 0)
	S031 = Part.Arc(P047, P048, P049)
	P050 = App.Vector(10.2690, 3.2654, 0)
	S032 = Part.LineSegment(P049, P050)
	P051 = App.Vector(9.7043, 3.6910, 0)
	P052 = App.Vector(10.1298, 4.2557, 0)
	S033 = Part.Arc(P050, P051, P052)
	P053 = App.Vector(10.0046, 5.1469, 0)
	S034 = Part.LineSegment(P052, P053)
	P054 = App.Vector(8.8130, 3.5657, 0)
	P055 = App.Vector(10.3943, 2.3742, 0)
	S035 = Part.Arc(P053, P054, P055)
	P056 = App.Vector(18.9106, 3.5711, 0)
	S036 = Part.LineSegment(P055, P056)
	P057 = App.Vector(19.4753, 3.1455, 0)
	P058 = App.Vector(19.0497, 2.5808, 0)
	S037 = Part.Arc(P056, P057, P058)
	P059 = App.Vector(11.1276, 1.4674, 0)
	S038 = Part.LineSegment(P058, P059)
	P060 = App.Vector(9.9361, -0.1138, 0)
	P061 = App.Vector(11.5173, -1.3053, 0)
	S039 = Part.Arc(P059, P060, P061)
	P062 = App.Vector(19.4394, -0.1920, 0)
	S040 = Part.LineSegment(P061, P062)
	P063 = App.Vector(20.0041, -0.6175, 0)
	P064 = App.Vector(19.5786, -1.1822, 0)
	S041 = Part.Arc(P062, P063, P064)
	P065 = App.Vector(11.6564, -2.2956, 0)
	S042 = Part.LineSegment(P064, P065)
	P066 = App.Vector(10.9661, -2.5973, 0)
	P067 = App.Vector(10.5321, -3.2131, 0)
	S043 = Part.Arc(P065, P066, P067)
	P068 = App.Vector(9.5263, -5.5000, 0)
	S044 = Part.LineSegment(P067, P068)
	P069 = App.Vector(21.6506, -12.5000, 0)
	S045 = Part.LineSegment(P068, P069)
	P070 = App.Vector(21.6506, 12.5000, 0)
	P071 = App.Vector(0.0000, 25.0000, 0)
	S046 = Part.Arc(P069, P070, P071)
	P072 = App.Vector(0.0000, 11.0000, 0)
	S047 = Part.LineSegment(P071, P072)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_haxis_guidance_faceProfile_Fa0():
	FC000 = ctr_face_haxis_guidance_faceProfile_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def haxis_guidance_faceProfile():
	FA000 = face_haxis_guidance_faceProfile_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_haxis_guidance_faceSide_Fa0_Ctr0():
	P000 = App.Vector(0.0000, -12.5000, 0)
	P001 = App.Vector(13.0000, -12.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(13.0000, 25.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 25.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, -12.5000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_haxis_guidance_faceSide_Fa0():
	FC000 = ctr_face_haxis_guidance_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def haxis_guidance_faceSide():
	FA000 = face_haxis_guidance_faceSide_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_haxis_guidance_profile():
	FIG = haxis_guidance_faceProfile()
	VEX = FIG.extrude(App.Vector(0, 0, 13))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(0, 0, 0))
	return VFP
subpax_haxis_guidance_profile = fex_subpax_haxis_guidance_profile()

pax_haxis_guidance = subpax_haxis_guidance_profile

pax_haxis_guidance.check()
#pax_haxis_guidance.exportBrep(f"{outFileName}.brep")
#pax_haxis_guidance.exportIges(f"{outFileName}.igs")
#pax_haxis_guidance.exportStep(f"{outFileName}.stp")
pax_haxis_guidance.exportStl(f"{outFileName}.stl")

