# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "spider"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_spider_faceLegs_Fa0_Ctr0():
	P000 = App.Vector(2.5000, -1.6583, 0)
	P001 = App.Vector(2.5000, -8.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(34.2132, -8.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(36.1266, -8.3806, 0)
	P004 = App.Vector(37.7487, -9.4645, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(70.7107, -42.4264, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(67.1751, -45.9619, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(34.2132, -13.0000, 0)
	S005 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-34.2132, -13.0000, 0)
	S006 = Part.LineSegment(P007, P008)
	P009 = App.Vector(-67.1751, -45.9619, 0)
	S007 = Part.LineSegment(P008, P009)
	P010 = App.Vector(-70.7107, -42.4264, 0)
	S008 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-37.7487, -9.4645, 0)
	S009 = Part.LineSegment(P010, P011)
	P012 = App.Vector(-36.1266, -8.3806, 0)
	P013 = App.Vector(-34.2132, -8.0000, 0)
	S010 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(-2.5000, -8.0000, 0)
	S011 = Part.LineSegment(P013, P014)
	P015 = App.Vector(-2.5000, -1.6583, 0)
	S012 = Part.LineSegment(P014, P015)
	P016 = App.Vector(0.0000, 3.0000, 0)
	P017 = App.Vector(2.5000, -1.6583, 0)
	S013 = Part.Arc(P015, P016, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_spider_faceLegs_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_spider_faceLegs_Fa0():
	FC000 = ctr_face_spider_faceLegs_Fa0_Ctr0()
	FC001 = ctr_face_spider_faceLegs_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def spider_faceLegs():
	FA000 = face_spider_faceLegs_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_spider_faceTube_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(3.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_spider_faceTube_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_spider_faceTube_Fa0():
	FC000 = ctr_face_spider_faceTube_Fa0_Ctr0()
	FC001 = ctr_face_spider_faceTube_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_spider_faceTube_Fa1_Ctr0():
	P000 = App.Vector(72.4784, -40.6586, 0)
	P001 = App.Vector(79.5495, -47.7297, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(72.4784, -54.8008, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(65.4074, -47.7297, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(72.4784, -40.6586, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_spider_faceTube_Fa1_Ctr1():
	P000 = App.Vector(72.4784, -43.4871, 0)
	P001 = App.Vector(76.7211, -47.7297, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(72.4784, -51.9723, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(68.2358, -47.7297, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(72.4784, -43.4871, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spider_faceTube_Fa1():
	FC000 = ctr_face_spider_faceTube_Fa1_Ctr0()
	FC001 = ctr_face_spider_faceTube_Fa1_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_spider_faceTube_Fa2_Ctr0():
	P000 = App.Vector(-72.4784, -40.6586, 0)
	P001 = App.Vector(-65.4074, -47.7297, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-72.4784, -54.8008, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-79.5495, -47.7297, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-72.4784, -40.6586, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_spider_faceTube_Fa2_Ctr1():
	P000 = App.Vector(-72.4784, -43.4871, 0)
	P001 = App.Vector(-68.2358, -47.7297, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-72.4784, -51.9723, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-76.7211, -47.7297, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-72.4784, -43.4871, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_spider_faceTube_Fa2():
	FC000 = ctr_face_spider_faceTube_Fa2_Ctr0()
	FC001 = ctr_face_spider_faceTube_Fa2_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def spider_faceTube():
	FA000 = face_spider_faceTube_Fa0()
	FA001 = face_spider_faceTube_Fa1()
	FA002 = face_spider_faceTube_Fa2()
	rOneFig = FA000.fuse([FA001, FA002])
	rOneFig.check()
	return rOneFig

def spider_faceBody():
	rOneFig = undefined
	rOneFig.check()
	return rOneFig

def fex_subpax_spider_tube():
	FIG = spider_faceTube()
	VEX = FIG.extrude(App.Vector(0, 0, 38.4))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_spider_tube = fex_subpax_spider_tube()

def fex_subpax_spider_leg_0():
	FIG = spider_faceLegs()
	VEX = FIG.extrude(App.Vector(0, 0, 0.64))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_spider_leg_0 = fex_subpax_spider_leg_0()

def fex_subpax_spider_leg_1():
	FIG = spider_faceLegs()
	VEX = FIG.extrude(App.Vector(0, 0, 0.64))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 7.5520))
	return VFP
subpax_spider_leg_1 = fex_subpax_spider_leg_1()

def fex_subpax_spider_leg_2():
	FIG = spider_faceLegs()
	VEX = FIG.extrude(App.Vector(0, 0, 0.64))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 15.1040))
	return VFP
subpax_spider_leg_2 = fex_subpax_spider_leg_2()

def fex_subpax_spider_leg_3():
	FIG = spider_faceLegs()
	VEX = FIG.extrude(App.Vector(0, 0, 0.64))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 22.6560))
	return VFP
subpax_spider_leg_3 = fex_subpax_spider_leg_3()

def fex_subpax_spider_leg_4():
	FIG = spider_faceLegs()
	VEX = FIG.extrude(App.Vector(0, 0, 0.64))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 30.2080))
	return VFP
subpax_spider_leg_4 = fex_subpax_spider_leg_4()

def fex_subpax_spider_leg_5():
	FIG = spider_faceLegs()
	VEX = FIG.extrude(App.Vector(0, 0, 0.64))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 37.7600))
	return VFP
subpax_spider_leg_5 = fex_subpax_spider_leg_5()

def fvol_pax_spider():
	V000 = subpax_spider_tube
	V001 = V000.fuse(subpax_spider_leg_0)
	V002 = V001.fuse(subpax_spider_leg_1)
	V003 = V002.fuse(subpax_spider_leg_2)
	V004 = V003.fuse(subpax_spider_leg_3)
	V005 = V004.fuse(subpax_spider_leg_4)
	V006 = V005.fuse(subpax_spider_leg_5)
	VFC = V006.removeSplitter()
	return VFC
pax_spider = fvol_pax_spider()


pax_spider.check()
#pax_spider.exportBrep(f"{outFileName}.brep")
#pax_spider.exportIges(f"{outFileName}.igs")
#pax_spider.exportStep(f"{outFileName}.stp")
pax_spider.exportStl(f"{outFileName}.stl")

