# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "base"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_base_faceCut_Fa0_Ctr0():
	P000 = App.Vector(49.0000, 0.0000, 0)
	P001 = App.Vector(49.0000, 2.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(44.0000, 2.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(44.0000, 60.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(42.0000, 60.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(42.0000, 2.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(40.0000, 2.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(40.0000, 0.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(49.0000, 0.0000, 0)
	S007 = Part.LineSegment(P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_base_faceCut_Fa0():
	FC000 = ctr_face_base_faceCut_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def base_faceCut():
	FA000 = face_base_faceCut_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_base_faceTop_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(44.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(38.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(40.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(39.2314, 7.8036, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(36.9552, 15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(33.2588, 22.2228, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(28.2843, 28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(22.2228, 33.2588, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.3073, 36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr9():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(7.8036, 39.2314, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr10():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(0.0000, 40.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr11():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-7.8036, 39.2314, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr12():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.3073, 36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr13():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-22.2228, 33.2588, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr14():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-28.2843, 28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr15():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-33.2588, 22.2228, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr16():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-36.9552, 15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr17():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-39.2314, 7.8036, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr18():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-40.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr19():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-39.2314, -7.8036, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr20():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-36.9552, -15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr21():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-33.2588, -22.2228, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr22():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-28.2843, -28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr23():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-22.2228, -33.2588, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr24():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.3073, -36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr25():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-7.8036, -39.2314, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr26():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-0.0000, -40.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr27():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(7.8036, -39.2314, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr28():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.3073, -36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr29():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(22.2228, -33.2588, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr30():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(28.2843, -28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr31():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(33.2588, -22.2228, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr32():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(36.9552, -15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_base_faceTop_Fa0_Ctr33():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(39.2314, -7.8036, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_base_faceTop_Fa0():
	FC000 = ctr_face_base_faceTop_Fa0_Ctr0()
	FC001 = ctr_face_base_faceTop_Fa0_Ctr1()
	FC002 = ctr_face_base_faceTop_Fa0_Ctr2()
	FC003 = ctr_face_base_faceTop_Fa0_Ctr3()
	FC004 = ctr_face_base_faceTop_Fa0_Ctr4()
	FC005 = ctr_face_base_faceTop_Fa0_Ctr5()
	FC006 = ctr_face_base_faceTop_Fa0_Ctr6()
	FC007 = ctr_face_base_faceTop_Fa0_Ctr7()
	FC008 = ctr_face_base_faceTop_Fa0_Ctr8()
	FC009 = ctr_face_base_faceTop_Fa0_Ctr9()
	FC010 = ctr_face_base_faceTop_Fa0_Ctr10()
	FC011 = ctr_face_base_faceTop_Fa0_Ctr11()
	FC012 = ctr_face_base_faceTop_Fa0_Ctr12()
	FC013 = ctr_face_base_faceTop_Fa0_Ctr13()
	FC014 = ctr_face_base_faceTop_Fa0_Ctr14()
	FC015 = ctr_face_base_faceTop_Fa0_Ctr15()
	FC016 = ctr_face_base_faceTop_Fa0_Ctr16()
	FC017 = ctr_face_base_faceTop_Fa0_Ctr17()
	FC018 = ctr_face_base_faceTop_Fa0_Ctr18()
	FC019 = ctr_face_base_faceTop_Fa0_Ctr19()
	FC020 = ctr_face_base_faceTop_Fa0_Ctr20()
	FC021 = ctr_face_base_faceTop_Fa0_Ctr21()
	FC022 = ctr_face_base_faceTop_Fa0_Ctr22()
	FC023 = ctr_face_base_faceTop_Fa0_Ctr23()
	FC024 = ctr_face_base_faceTop_Fa0_Ctr24()
	FC025 = ctr_face_base_faceTop_Fa0_Ctr25()
	FC026 = ctr_face_base_faceTop_Fa0_Ctr26()
	FC027 = ctr_face_base_faceTop_Fa0_Ctr27()
	FC028 = ctr_face_base_faceTop_Fa0_Ctr28()
	FC029 = ctr_face_base_faceTop_Fa0_Ctr29()
	FC030 = ctr_face_base_faceTop_Fa0_Ctr30()
	FC031 = ctr_face_base_faceTop_Fa0_Ctr31()
	FC032 = ctr_face_base_faceTop_Fa0_Ctr32()
	FC033 = ctr_face_base_faceTop_Fa0_Ctr33()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008, FC009, FC010, FC011, FC012, FC013, FC014, FC015, FC016, FC017, FC018, FC019, FC020, FC021, FC022, FC023, FC024, FC025, FC026, FC027, FC028, FC029, FC030, FC031, FC032, FC033])
	rOneFace.check()
	return rOneFace

def base_faceTop():
	FA000 = face_base_faceTop_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_base_faceHollow_Fa0_Ctr0():
	P000 = App.Vector(5.0000, 11.0000, 0)
	P001 = App.Vector(5.0000, 31.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(0.0000, 36.0000, 0)
	P003 = App.Vector(-5.0000, 31.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-5.0000, 11.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-0.0000, 6.0000, 0)
	P006 = App.Vector(5.0000, 11.0000, 0)
	S003 = Part.Arc(P004, P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_base_faceHollow_Fa0():
	FC000 = ctr_face_base_faceHollow_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def base_faceHollow():
	FA000 = face_base_faceHollow_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_base_cut():
	FIG = base_faceCut()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(1.5708, 0.0000, 0.0000))
	return VFP
subpax_base_cut = fex_subpax_base_cut()

def fex_subpax_base_top():
	FIG = base_faceTop()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 58.0000))
	return VFP
subpax_base_top = fex_subpax_base_top()

def fex_subpax_base_hollow_0():
	FIG = base_faceHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 51))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_base_hollow_0 = fex_subpax_base_hollow_0()

def fex_subpax_base_hollow_1():
	FIG = base_faceHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 51))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 22.5000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_base_hollow_1 = fex_subpax_base_hollow_1()

def fex_subpax_base_hollow_2():
	FIG = base_faceHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 51))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 45.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_base_hollow_2 = fex_subpax_base_hollow_2()

def fex_subpax_base_hollow_3():
	FIG = base_faceHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 51))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 67.5000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_base_hollow_3 = fex_subpax_base_hollow_3()

def fex_subpax_base_hollow_4():
	FIG = base_faceHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 51))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_base_hollow_4 = fex_subpax_base_hollow_4()

def fex_subpax_base_hollow_5():
	FIG = base_faceHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 51))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 112.5000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_base_hollow_5 = fex_subpax_base_hollow_5()

def fex_subpax_base_hollow_6():
	FIG = base_faceHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 51))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 135.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_base_hollow_6 = fex_subpax_base_hollow_6()

def fex_subpax_base_hollow_7():
	FIG = base_faceHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 51))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 157.5000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_base_hollow_7 = fex_subpax_base_hollow_7()

def fex_subpax_base_hollow_8():
	FIG = base_faceHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 51))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 180.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_base_hollow_8 = fex_subpax_base_hollow_8()

def fex_subpax_base_hollow_9():
	FIG = base_faceHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 51))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 202.5000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_base_hollow_9 = fex_subpax_base_hollow_9()

def fex_subpax_base_hollow_10():
	FIG = base_faceHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 51))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 225.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_base_hollow_10 = fex_subpax_base_hollow_10()

def fex_subpax_base_hollow_11():
	FIG = base_faceHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 51))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 247.5000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_base_hollow_11 = fex_subpax_base_hollow_11()

def fex_subpax_base_hollow_12():
	FIG = base_faceHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 51))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 270.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_base_hollow_12 = fex_subpax_base_hollow_12()

def fex_subpax_base_hollow_13():
	FIG = base_faceHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 51))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 292.5000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_base_hollow_13 = fex_subpax_base_hollow_13()

def fex_subpax_base_hollow_14():
	FIG = base_faceHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 51))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 315.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_base_hollow_14 = fex_subpax_base_hollow_14()

def fex_subpax_base_hollow_15():
	FIG = base_faceHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 51))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 337.5000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_base_hollow_15 = fex_subpax_base_hollow_15()

ipax_base_hollows = subpax_base_hollow_0.fuse([subpax_base_hollow_1, subpax_base_hollow_2, subpax_base_hollow_3, subpax_base_hollow_4, subpax_base_hollow_5, subpax_base_hollow_6, subpax_base_hollow_7, subpax_base_hollow_8, subpax_base_hollow_9, subpax_base_hollow_10, subpax_base_hollow_11, subpax_base_hollow_12, subpax_base_hollow_13, subpax_base_hollow_14, subpax_base_hollow_15])
ipax_base_cylinder = subpax_base_cut.cut([ipax_base_hollows])
pax_base = ipax_base_cylinder.fuse([subpax_base_top])

pax_base.check()
#pax_base.exportBrep(f"{outFileName}.brep")
#pax_base.exportIges(f"{outFileName}.igs")
#pax_base.exportStep(f"{outFileName}.stp")
pax_base.exportStl(f"{outFileName}.stl")

