# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "pole_static"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_pole_static_poleCut_Fa0_Ctr0():
	P000 = App.Vector(44.0000, 0.0000, 0)
	P001 = App.Vector(44.0000, 80.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(35.0000, 300.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(33.0017, 299.9183, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(42.0000, 79.9591, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(42.0000, 0.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(44.0000, 0.0000, 0)
	S005 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_pole_static_poleCut_Fa0():
	FC000 = ctr_face_pole_static_poleCut_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def pole_static_poleCut():
	FA000 = face_pole_static_poleCut_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pole_static_poleFace_Fa0_Ctr0():
	P000 = App.Vector(12.5000, 62.5000, 0)
	P001 = App.Vector(0.0000, 75.0000, 0)
	P002 = App.Vector(-12.5000, 62.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-12.5000, 17.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-0.0000, 5.0000, 0)
	P005 = App.Vector(12.5000, 17.5000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(12.5000, 62.5000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_pole_static_poleFace_Fa0_Ctr1():
	P000 = App.Vector(9.5000, 62.5000, 0)
	P001 = App.Vector(0.0000, 72.0000, 0)
	P002 = App.Vector(-9.5000, 62.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-9.5000, 17.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-0.0000, 8.0000, 0)
	P005 = App.Vector(9.5000, 17.5000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(9.5000, 62.5000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_pole_static_poleFace_Fa0():
	FC000 = ctr_face_pole_static_poleFace_Fa0_Ctr0()
	FC001 = ctr_face_pole_static_poleFace_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def pole_static_poleFace():
	FA000 = face_pole_static_poleFace_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pole_static_poleBottom_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(44.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(38.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(40.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(39.2314, 7.8036, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(36.9552, 15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(33.2588, 22.2228, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(28.2843, 28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(22.2228, 33.2588, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.3073, 36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr9():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(7.8036, 39.2314, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr10():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(0.0000, 40.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr11():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-7.8036, 39.2314, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr12():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.3073, 36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr13():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-22.2228, 33.2588, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr14():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-28.2843, 28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr15():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-33.2588, 22.2228, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr16():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-36.9552, 15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr17():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-39.2314, 7.8036, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr18():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-40.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr19():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-39.2314, -7.8036, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr20():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-36.9552, -15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr21():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-33.2588, -22.2228, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr22():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-28.2843, -28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr23():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-22.2228, -33.2588, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr24():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.3073, -36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr25():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-7.8036, -39.2314, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr26():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-0.0000, -40.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr27():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(7.8036, -39.2314, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr28():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.3073, -36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr29():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(22.2228, -33.2588, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr30():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(28.2843, -28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr31():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(33.2588, -22.2228, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr32():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(36.9552, -15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_poleBottom_Fa0_Ctr33():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(39.2314, -7.8036, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_pole_static_poleBottom_Fa0():
	FC000 = ctr_face_pole_static_poleBottom_Fa0_Ctr0()
	FC001 = ctr_face_pole_static_poleBottom_Fa0_Ctr1()
	FC002 = ctr_face_pole_static_poleBottom_Fa0_Ctr2()
	FC003 = ctr_face_pole_static_poleBottom_Fa0_Ctr3()
	FC004 = ctr_face_pole_static_poleBottom_Fa0_Ctr4()
	FC005 = ctr_face_pole_static_poleBottom_Fa0_Ctr5()
	FC006 = ctr_face_pole_static_poleBottom_Fa0_Ctr6()
	FC007 = ctr_face_pole_static_poleBottom_Fa0_Ctr7()
	FC008 = ctr_face_pole_static_poleBottom_Fa0_Ctr8()
	FC009 = ctr_face_pole_static_poleBottom_Fa0_Ctr9()
	FC010 = ctr_face_pole_static_poleBottom_Fa0_Ctr10()
	FC011 = ctr_face_pole_static_poleBottom_Fa0_Ctr11()
	FC012 = ctr_face_pole_static_poleBottom_Fa0_Ctr12()
	FC013 = ctr_face_pole_static_poleBottom_Fa0_Ctr13()
	FC014 = ctr_face_pole_static_poleBottom_Fa0_Ctr14()
	FC015 = ctr_face_pole_static_poleBottom_Fa0_Ctr15()
	FC016 = ctr_face_pole_static_poleBottom_Fa0_Ctr16()
	FC017 = ctr_face_pole_static_poleBottom_Fa0_Ctr17()
	FC018 = ctr_face_pole_static_poleBottom_Fa0_Ctr18()
	FC019 = ctr_face_pole_static_poleBottom_Fa0_Ctr19()
	FC020 = ctr_face_pole_static_poleBottom_Fa0_Ctr20()
	FC021 = ctr_face_pole_static_poleBottom_Fa0_Ctr21()
	FC022 = ctr_face_pole_static_poleBottom_Fa0_Ctr22()
	FC023 = ctr_face_pole_static_poleBottom_Fa0_Ctr23()
	FC024 = ctr_face_pole_static_poleBottom_Fa0_Ctr24()
	FC025 = ctr_face_pole_static_poleBottom_Fa0_Ctr25()
	FC026 = ctr_face_pole_static_poleBottom_Fa0_Ctr26()
	FC027 = ctr_face_pole_static_poleBottom_Fa0_Ctr27()
	FC028 = ctr_face_pole_static_poleBottom_Fa0_Ctr28()
	FC029 = ctr_face_pole_static_poleBottom_Fa0_Ctr29()
	FC030 = ctr_face_pole_static_poleBottom_Fa0_Ctr30()
	FC031 = ctr_face_pole_static_poleBottom_Fa0_Ctr31()
	FC032 = ctr_face_pole_static_poleBottom_Fa0_Ctr32()
	FC033 = ctr_face_pole_static_poleBottom_Fa0_Ctr33()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008, FC009, FC010, FC011, FC012, FC013, FC014, FC015, FC016, FC017, FC018, FC019, FC020, FC021, FC022, FC023, FC024, FC025, FC026, FC027, FC028, FC029, FC030, FC031, FC032, FC033])
	rOneFace.check()
	return rOneFace

def pole_static_poleBottom():
	FA000 = face_pole_static_poleBottom_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pole_static_emptyPole_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(47.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_emptyPole_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(42.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_pole_static_emptyPole_Fa0():
	FC000 = ctr_face_pole_static_emptyPole_Fa0_Ctr0()
	FC001 = ctr_face_pole_static_emptyPole_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def pole_static_emptyPole():
	FA000 = face_pole_static_emptyPole_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pole_static_emptyDoor_Fa0_Ctr0():
	P000 = App.Vector(9.5000, 62.5000, 0)
	P001 = App.Vector(0.0000, 72.0000, 0)
	P002 = App.Vector(-9.5000, 62.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-9.5000, 17.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-0.0000, 8.0000, 0)
	P005 = App.Vector(9.5000, 17.5000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(9.5000, 62.5000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_pole_static_emptyDoor_Fa0():
	FC000 = ctr_face_pole_static_emptyDoor_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def pole_static_emptyDoor():
	FA000 = face_pole_static_emptyDoor_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pole_static_holderB2Section_Fa0_Ctr0():
	P000 = App.Vector(32.9742, -1.0000, 0)
	P001 = App.Vector(33.4483, -1.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(33.8165, -10.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(35.8148, -9.9183, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(34.9967, 10.0817, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(32.9983, 10.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(33.3665, 1.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(32.9742, 1.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(32.9742, -1.0000, 0)
	S007 = Part.LineSegment(P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_pole_static_holderB2Section_Fa0():
	FC000 = ctr_face_pole_static_holderB2Section_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def pole_static_holderB2Section():
	FA000 = face_pole_static_holderB2Section_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pole_static_holderB2Top_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(33.3665, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_holderB2Top_Fa0_Ctr1():
	P000 = App.Vector(29.4812, -3.5935, 0)
	P001 = App.Vector(26.0574, -1.7639, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(25.0000, 0.0000, 0)
	P003 = App.Vector(26.0574, 1.7639, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(29.4812, 3.5935, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(31.2584, 5.5133, 0)
	P006 = App.Vector(31.4690, 8.1209, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(28.1458, 16.2500, 0)
	P008 = App.Vector(22.7674, 23.1925, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(20.4039, 24.3140, 0)
	P010 = App.Vector(17.8527, 23.7347, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(14.5563, 21.6844, 0)
	S006 = Part.LineSegment(P010, P011)
	P012 = App.Vector(12.5000, 21.6506, 0)
	P013 = App.Vector(11.5011, 23.4483, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(11.6285, 27.3282, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(10.8546, 29.8272, 0)
	P016 = App.Vector(8.7016, 31.3135, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(-0.0000, 32.5000, 0)
	P018 = App.Vector(-8.7016, 31.3135, 0)
	S010 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-10.8546, 29.8272, 0)
	P020 = App.Vector(-11.6285, 27.3282, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(-11.5011, 23.4483, 0)
	S012 = Part.LineSegment(P020, P021)
	P022 = App.Vector(-12.5000, 21.6506, 0)
	P023 = App.Vector(-14.5563, 21.6844, 0)
	S013 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(-17.8527, 23.7347, 0)
	S014 = Part.LineSegment(P023, P024)
	P025 = App.Vector(-20.4039, 24.3140, 0)
	P026 = App.Vector(-22.7674, 23.1925, 0)
	S015 = Part.Arc(P024, P025, P026)
	P027 = App.Vector(-28.1458, 16.2500, 0)
	P028 = App.Vector(-31.4690, 8.1209, 0)
	S016 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-31.2584, 5.5133, 0)
	P030 = App.Vector(-29.4812, 3.5935, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-26.0574, 1.7639, 0)
	S018 = Part.LineSegment(P030, P031)
	P032 = App.Vector(-25.0000, 0.0000, 0)
	P033 = App.Vector(-26.0574, -1.7639, 0)
	S019 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-29.4812, -3.5935, 0)
	S020 = Part.LineSegment(P033, P034)
	P035 = App.Vector(-31.2584, -5.5133, 0)
	P036 = App.Vector(-31.4690, -8.1209, 0)
	S021 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-28.1458, -16.2500, 0)
	P038 = App.Vector(-22.7674, -23.1925, 0)
	S022 = Part.Arc(P036, P037, P038)
	P039 = App.Vector(-20.4039, -24.3140, 0)
	P040 = App.Vector(-17.8527, -23.7347, 0)
	S023 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-14.5563, -21.6844, 0)
	S024 = Part.LineSegment(P040, P041)
	P042 = App.Vector(-12.5000, -21.6506, 0)
	P043 = App.Vector(-11.5011, -23.4483, 0)
	S025 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(-11.6285, -27.3282, 0)
	S026 = Part.LineSegment(P043, P044)
	P045 = App.Vector(-10.8546, -29.8272, 0)
	P046 = App.Vector(-8.7016, -31.3135, 0)
	S027 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(-0.0000, -32.5000, 0)
	P048 = App.Vector(8.7016, -31.3135, 0)
	S028 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(10.8546, -29.8272, 0)
	P050 = App.Vector(11.6285, -27.3282, 0)
	S029 = Part.Arc(P048, P049, P050)
	P051 = App.Vector(11.5011, -23.4483, 0)
	S030 = Part.LineSegment(P050, P051)
	P052 = App.Vector(12.5000, -21.6506, 0)
	P053 = App.Vector(14.5563, -21.6844, 0)
	S031 = Part.Arc(P051, P052, P053)
	P054 = App.Vector(17.8527, -23.7347, 0)
	S032 = Part.LineSegment(P053, P054)
	P055 = App.Vector(20.4039, -24.3140, 0)
	P056 = App.Vector(22.7674, -23.1925, 0)
	S033 = Part.Arc(P054, P055, P056)
	P057 = App.Vector(28.1458, -16.2500, 0)
	P058 = App.Vector(31.4690, -8.1209, 0)
	S034 = Part.Arc(P056, P057, P058)
	P059 = App.Vector(31.2584, -5.5133, 0)
	P060 = App.Vector(29.4812, -3.5935, 0)
	S035 = Part.Arc(P058, P059, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_pole_static_holderB2Top_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(27.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_holderB2Top_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(13.5000, 23.3827, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_holderB2Top_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-13.5000, 23.3827, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_holderB2Top_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-27.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_holderB2Top_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-13.5000, -23.3827, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_holderB2Top_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(13.5000, -23.3827, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_pole_static_holderB2Top_Fa0():
	FC000 = ctr_face_pole_static_holderB2Top_Fa0_Ctr0()
	FC001 = ctr_face_pole_static_holderB2Top_Fa0_Ctr1()
	FC002 = ctr_face_pole_static_holderB2Top_Fa0_Ctr2()
	FC003 = ctr_face_pole_static_holderB2Top_Fa0_Ctr3()
	FC004 = ctr_face_pole_static_holderB2Top_Fa0_Ctr4()
	FC005 = ctr_face_pole_static_holderB2Top_Fa0_Ctr5()
	FC006 = ctr_face_pole_static_holderB2Top_Fa0_Ctr6()
	FC007 = ctr_face_pole_static_holderB2Top_Fa0_Ctr7()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007])
	rOneFace.check()
	return rOneFace

def pole_static_holderB2Top():
	FA000 = face_pole_static_holderB2Top_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pole_static_holderB1Section_Fa0_Ctr0():
	P000 = App.Vector(38.9969, -1.0000, 0)
	P001 = App.Vector(39.9938, -1.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(40.3620, -10.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(42.3603, -9.9183, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(41.5421, 10.0817, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(39.5438, 10.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(39.9120, 1.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(38.9969, 1.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(38.9969, -1.0000, 0)
	S007 = Part.LineSegment(P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_pole_static_holderB1Section_Fa0():
	FC000 = ctr_face_pole_static_holderB1Section_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def pole_static_holderB1Section():
	FA000 = face_pole_static_holderB1Section_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pole_static_holderB1Top_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(39.9120, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_holderB1Top_Fa0_Ctr1():
	P000 = App.Vector(34.1305, -4.0294, 0)
	P001 = App.Vector(26.4710, -1.9288, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(25.0000, 0.0000, 0)
	P003 = App.Vector(26.4710, 1.9288, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(34.1305, 4.0294, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(36.5147, 5.8493, 0)
	P006 = App.Vector(36.9635, 8.8148, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(32.9090, 19.0000, 0)
	P008 = App.Vector(26.1156, 27.6039, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(23.3229, 28.6980, 0)
	P010 = App.Vector(20.5548, 27.5432, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(14.9059, 21.9602, 0)
	S006 = Part.LineSegment(P010, P011)
	P012 = App.Vector(12.5000, 21.6506, 0)
	P013 = App.Vector(11.5651, 23.8890, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(13.5757, 31.5726, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(13.1917, 34.5473, 0)
	P016 = App.Vector(10.8479, 36.4187, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(-0.0000, 38.0000, 0)
	P018 = App.Vector(-10.8479, 36.4187, 0)
	S010 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-13.1917, 34.5473, 0)
	P020 = App.Vector(-13.5757, 31.5726, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(-11.5651, 23.8890, 0)
	S012 = Part.LineSegment(P020, P021)
	P022 = App.Vector(-12.5000, 21.6506, 0)
	P023 = App.Vector(-14.9059, 21.9602, 0)
	S013 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(-20.5548, 27.5432, 0)
	S014 = Part.LineSegment(P023, P024)
	P025 = App.Vector(-23.3229, 28.6980, 0)
	P026 = App.Vector(-26.1156, 27.6039, 0)
	S015 = Part.Arc(P024, P025, P026)
	P027 = App.Vector(-32.9090, 19.0000, 0)
	P028 = App.Vector(-36.9635, 8.8148, 0)
	S016 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-36.5147, 5.8493, 0)
	P030 = App.Vector(-34.1305, 4.0294, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-26.4710, 1.9288, 0)
	S018 = Part.LineSegment(P030, P031)
	P032 = App.Vector(-25.0000, 0.0000, 0)
	P033 = App.Vector(-26.4710, -1.9288, 0)
	S019 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-34.1305, -4.0294, 0)
	S020 = Part.LineSegment(P033, P034)
	P035 = App.Vector(-36.5147, -5.8493, 0)
	P036 = App.Vector(-36.9635, -8.8148, 0)
	S021 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-32.9090, -19.0000, 0)
	P038 = App.Vector(-26.1156, -27.6039, 0)
	S022 = Part.Arc(P036, P037, P038)
	P039 = App.Vector(-23.3229, -28.6980, 0)
	P040 = App.Vector(-20.5548, -27.5432, 0)
	S023 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-14.9059, -21.9602, 0)
	S024 = Part.LineSegment(P040, P041)
	P042 = App.Vector(-12.5000, -21.6506, 0)
	P043 = App.Vector(-11.5651, -23.8890, 0)
	S025 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(-13.5757, -31.5726, 0)
	S026 = Part.LineSegment(P043, P044)
	P045 = App.Vector(-13.1917, -34.5473, 0)
	P046 = App.Vector(-10.8479, -36.4187, 0)
	S027 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(0.0000, -38.0000, 0)
	P048 = App.Vector(10.8479, -36.4187, 0)
	S028 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(13.1917, -34.5473, 0)
	P050 = App.Vector(13.5757, -31.5726, 0)
	S029 = Part.Arc(P048, P049, P050)
	P051 = App.Vector(11.5651, -23.8890, 0)
	S030 = Part.LineSegment(P050, P051)
	P052 = App.Vector(12.5000, -21.6506, 0)
	P053 = App.Vector(14.9059, -21.9602, 0)
	S031 = Part.Arc(P051, P052, P053)
	P054 = App.Vector(20.5548, -27.5432, 0)
	S032 = Part.LineSegment(P053, P054)
	P055 = App.Vector(23.3229, -28.6980, 0)
	P056 = App.Vector(26.1156, -27.6039, 0)
	S033 = Part.Arc(P054, P055, P056)
	P057 = App.Vector(32.9090, -19.0000, 0)
	P058 = App.Vector(36.9635, -8.8148, 0)
	S034 = Part.Arc(P056, P057, P058)
	P059 = App.Vector(36.5147, -5.8493, 0)
	P060 = App.Vector(34.1305, -4.0294, 0)
	S035 = Part.Arc(P058, P059, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_pole_static_holderB1Top_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(27.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_holderB1Top_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(13.5000, 23.3827, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_holderB1Top_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-13.5000, 23.3827, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_holderB1Top_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-27.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_holderB1Top_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-13.5000, -23.3827, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_holderB1Top_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(13.5000, -23.3827, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_pole_static_holderB1Top_Fa0():
	FC000 = ctr_face_pole_static_holderB1Top_Fa0_Ctr0()
	FC001 = ctr_face_pole_static_holderB1Top_Fa0_Ctr1()
	FC002 = ctr_face_pole_static_holderB1Top_Fa0_Ctr2()
	FC003 = ctr_face_pole_static_holderB1Top_Fa0_Ctr3()
	FC004 = ctr_face_pole_static_holderB1Top_Fa0_Ctr4()
	FC005 = ctr_face_pole_static_holderB1Top_Fa0_Ctr5()
	FC006 = ctr_face_pole_static_holderB1Top_Fa0_Ctr6()
	FC007 = ctr_face_pole_static_holderB1Top_Fa0_Ctr7()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007])
	rOneFace.check()
	return rOneFace

def pole_static_holderB1Top():
	FA000 = face_pole_static_holderB1Top_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pole_static_holderASection_Fa0_Ctr0():
	P000 = App.Vector(40.8151, -1.0000, 0)
	P001 = App.Vector(41.6301, -1.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(41.9983, -10.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(43.9967, -9.9183, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(43.1785, 10.0817, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(41.1801, 10.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(41.5483, 1.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(40.8151, 1.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(40.8151, -1.0000, 0)
	S007 = Part.LineSegment(P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_pole_static_holderASection_Fa0():
	FC000 = ctr_face_pole_static_holderASection_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def pole_static_holderASection():
	FA000 = face_pole_static_holderASection_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pole_static_holderATop_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(41.5483, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_holderATop_Fa0_Ctr1():
	P000 = App.Vector(36.5875, -3.8447, 0)
	P001 = App.Vector(31.3013, -1.8740, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(30.0000, 0.0000, 0)
	P003 = App.Vector(31.3013, 1.8740, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(36.5875, 3.8447, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(38.6991, 5.6725, 0)
	P006 = App.Vector(39.1002, 8.4364, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(34.6410, 20.0000, 0)
	P008 = App.Vector(26.8562, 29.6436, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(24.2621, 30.6782, 0)
	P010 = App.Vector(21.6234, 29.7633, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(17.2736, 26.1708, 0)
	S006 = Part.LineSegment(P010, P011)
	P012 = App.Vector(15.0000, 25.9808, 0)
	P013 = App.Vector(14.0277, 28.0448, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(14.9641, 33.6081, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(14.4370, 36.3507, 0)
	P016 = App.Vector(12.2440, 38.0800, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(-0.0000, 40.0000, 0)
	P018 = App.Vector(-12.2440, 38.0800, 0)
	S010 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-14.4370, 36.3507, 0)
	P020 = App.Vector(-14.9641, 33.6081, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(-14.0277, 28.0448, 0)
	S012 = Part.LineSegment(P020, P021)
	P022 = App.Vector(-15.0000, 25.9808, 0)
	P023 = App.Vector(-17.2736, 26.1708, 0)
	S013 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(-21.6234, 29.7633, 0)
	S014 = Part.LineSegment(P023, P024)
	P025 = App.Vector(-24.2621, 30.6782, 0)
	P026 = App.Vector(-26.8562, 29.6436, 0)
	S015 = Part.Arc(P024, P025, P026)
	P027 = App.Vector(-34.6410, 20.0000, 0)
	P028 = App.Vector(-39.1002, 8.4364, 0)
	S016 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-38.6991, 5.6725, 0)
	P030 = App.Vector(-36.5875, 3.8447, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-31.3013, 1.8740, 0)
	S018 = Part.LineSegment(P030, P031)
	P032 = App.Vector(-30.0000, 0.0000, 0)
	P033 = App.Vector(-31.3013, -1.8740, 0)
	S019 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-36.5875, -3.8447, 0)
	S020 = Part.LineSegment(P033, P034)
	P035 = App.Vector(-38.6991, -5.6725, 0)
	P036 = App.Vector(-39.1002, -8.4364, 0)
	S021 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-34.6410, -20.0000, 0)
	P038 = App.Vector(-26.8562, -29.6436, 0)
	S022 = Part.Arc(P036, P037, P038)
	P039 = App.Vector(-24.2621, -30.6782, 0)
	P040 = App.Vector(-21.6234, -29.7633, 0)
	S023 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-17.2736, -26.1708, 0)
	S024 = Part.LineSegment(P040, P041)
	P042 = App.Vector(-15.0000, -25.9808, 0)
	P043 = App.Vector(-14.0277, -28.0448, 0)
	S025 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(-14.9641, -33.6081, 0)
	S026 = Part.LineSegment(P043, P044)
	P045 = App.Vector(-14.4370, -36.3507, 0)
	P046 = App.Vector(-12.2440, -38.0800, 0)
	S027 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(-0.0000, -40.0000, 0)
	P048 = App.Vector(12.2440, -38.0800, 0)
	S028 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(14.4370, -36.3507, 0)
	P050 = App.Vector(14.9641, -33.6081, 0)
	S029 = Part.Arc(P048, P049, P050)
	P051 = App.Vector(14.0277, -28.0448, 0)
	S030 = Part.LineSegment(P050, P051)
	P052 = App.Vector(15.0000, -25.9808, 0)
	P053 = App.Vector(17.2736, -26.1708, 0)
	S031 = Part.Arc(P051, P052, P053)
	P054 = App.Vector(21.6234, -29.7633, 0)
	S032 = Part.LineSegment(P053, P054)
	P055 = App.Vector(24.2621, -30.6782, 0)
	P056 = App.Vector(26.8562, -29.6436, 0)
	S033 = Part.Arc(P054, P055, P056)
	P057 = App.Vector(34.6410, -20.0000, 0)
	P058 = App.Vector(39.1002, -8.4364, 0)
	S034 = Part.Arc(P056, P057, P058)
	P059 = App.Vector(38.6991, -5.6725, 0)
	P060 = App.Vector(36.5875, -3.8447, 0)
	S035 = Part.Arc(P058, P059, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_pole_static_holderATop_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(32.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_holderATop_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(16.0000, 27.7128, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_holderATop_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-16.0000, 27.7128, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_holderATop_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-32.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_holderATop_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-16.0000, -27.7128, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pole_static_holderATop_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(16.0000, -27.7128, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_pole_static_holderATop_Fa0():
	FC000 = ctr_face_pole_static_holderATop_Fa0_Ctr0()
	FC001 = ctr_face_pole_static_holderATop_Fa0_Ctr1()
	FC002 = ctr_face_pole_static_holderATop_Fa0_Ctr2()
	FC003 = ctr_face_pole_static_holderATop_Fa0_Ctr3()
	FC004 = ctr_face_pole_static_holderATop_Fa0_Ctr4()
	FC005 = ctr_face_pole_static_holderATop_Fa0_Ctr5()
	FC006 = ctr_face_pole_static_holderATop_Fa0_Ctr6()
	FC007 = ctr_face_pole_static_holderATop_Fa0_Ctr7()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007])
	rOneFace.check()
	return rOneFace

def pole_static_holderATop():
	FA000 = face_pole_static_holderATop_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_vaxis_holderB2_facePetal_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(33.3665, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holderB2_facePetal_Fa0_Ctr1():
	P000 = App.Vector(29.4812, -3.5935, 0)
	P001 = App.Vector(26.0574, -1.7639, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(25.0000, 0.0000, 0)
	P003 = App.Vector(26.0574, 1.7639, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(29.4812, 3.5935, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(31.2584, 5.5133, 0)
	P006 = App.Vector(31.4690, 8.1209, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(28.1458, 16.2500, 0)
	P008 = App.Vector(22.7674, 23.1925, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(20.4039, 24.3140, 0)
	P010 = App.Vector(17.8527, 23.7347, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(14.5563, 21.6844, 0)
	S006 = Part.LineSegment(P010, P011)
	P012 = App.Vector(12.5000, 21.6506, 0)
	P013 = App.Vector(11.5011, 23.4483, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(11.6285, 27.3282, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(10.8546, 29.8272, 0)
	P016 = App.Vector(8.7016, 31.3135, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(-0.0000, 32.5000, 0)
	P018 = App.Vector(-8.7016, 31.3135, 0)
	S010 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-10.8546, 29.8272, 0)
	P020 = App.Vector(-11.6285, 27.3282, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(-11.5011, 23.4483, 0)
	S012 = Part.LineSegment(P020, P021)
	P022 = App.Vector(-12.5000, 21.6506, 0)
	P023 = App.Vector(-14.5563, 21.6844, 0)
	S013 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(-17.8527, 23.7347, 0)
	S014 = Part.LineSegment(P023, P024)
	P025 = App.Vector(-20.4039, 24.3140, 0)
	P026 = App.Vector(-22.7674, 23.1925, 0)
	S015 = Part.Arc(P024, P025, P026)
	P027 = App.Vector(-28.1458, 16.2500, 0)
	P028 = App.Vector(-31.4690, 8.1209, 0)
	S016 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-31.2584, 5.5133, 0)
	P030 = App.Vector(-29.4812, 3.5935, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-26.0574, 1.7639, 0)
	S018 = Part.LineSegment(P030, P031)
	P032 = App.Vector(-25.0000, 0.0000, 0)
	P033 = App.Vector(-26.0574, -1.7639, 0)
	S019 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-29.4812, -3.5935, 0)
	S020 = Part.LineSegment(P033, P034)
	P035 = App.Vector(-31.2584, -5.5133, 0)
	P036 = App.Vector(-31.4690, -8.1209, 0)
	S021 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-28.1458, -16.2500, 0)
	P038 = App.Vector(-22.7674, -23.1925, 0)
	S022 = Part.Arc(P036, P037, P038)
	P039 = App.Vector(-20.4039, -24.3140, 0)
	P040 = App.Vector(-17.8527, -23.7347, 0)
	S023 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-14.5563, -21.6844, 0)
	S024 = Part.LineSegment(P040, P041)
	P042 = App.Vector(-12.5000, -21.6506, 0)
	P043 = App.Vector(-11.5011, -23.4483, 0)
	S025 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(-11.6285, -27.3282, 0)
	S026 = Part.LineSegment(P043, P044)
	P045 = App.Vector(-10.8546, -29.8272, 0)
	P046 = App.Vector(-8.7016, -31.3135, 0)
	S027 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(-0.0000, -32.5000, 0)
	P048 = App.Vector(8.7016, -31.3135, 0)
	S028 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(10.8546, -29.8272, 0)
	P050 = App.Vector(11.6285, -27.3282, 0)
	S029 = Part.Arc(P048, P049, P050)
	P051 = App.Vector(11.5011, -23.4483, 0)
	S030 = Part.LineSegment(P050, P051)
	P052 = App.Vector(12.5000, -21.6506, 0)
	P053 = App.Vector(14.5563, -21.6844, 0)
	S031 = Part.Arc(P051, P052, P053)
	P054 = App.Vector(17.8527, -23.7347, 0)
	S032 = Part.LineSegment(P053, P054)
	P055 = App.Vector(20.4039, -24.3140, 0)
	P056 = App.Vector(22.7674, -23.1925, 0)
	S033 = Part.Arc(P054, P055, P056)
	P057 = App.Vector(28.1458, -16.2500, 0)
	P058 = App.Vector(31.4690, -8.1209, 0)
	S034 = Part.Arc(P056, P057, P058)
	P059 = App.Vector(31.2584, -5.5133, 0)
	P060 = App.Vector(29.4812, -3.5935, 0)
	S035 = Part.Arc(P058, P059, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_vaxis_holderB2_facePetal_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(27.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holderB2_facePetal_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(13.5000, 23.3827, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holderB2_facePetal_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-13.5000, 23.3827, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holderB2_facePetal_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-27.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holderB2_facePetal_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-13.5000, -23.3827, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holderB2_facePetal_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(13.5000, -23.3827, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_vaxis_holderB2_facePetal_Fa0():
	FC000 = ctr_face_vaxis_holderB2_facePetal_Fa0_Ctr0()
	FC001 = ctr_face_vaxis_holderB2_facePetal_Fa0_Ctr1()
	FC002 = ctr_face_vaxis_holderB2_facePetal_Fa0_Ctr2()
	FC003 = ctr_face_vaxis_holderB2_facePetal_Fa0_Ctr3()
	FC004 = ctr_face_vaxis_holderB2_facePetal_Fa0_Ctr4()
	FC005 = ctr_face_vaxis_holderB2_facePetal_Fa0_Ctr5()
	FC006 = ctr_face_vaxis_holderB2_facePetal_Fa0_Ctr6()
	FC007 = ctr_face_vaxis_holderB2_facePetal_Fa0_Ctr7()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007])
	rOneFace.check()
	return rOneFace

def vaxis_holderB2_facePetal():
	FA000 = face_vaxis_holderB2_facePetal_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_vaxis_holderB2_faceOuter_Fa0_Ctr0():
	P000 = App.Vector(32.9742, -1.0000, 0)
	P001 = App.Vector(33.4483, -1.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(33.8165, -10.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(35.8148, -9.9183, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(34.9967, 10.0817, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(32.9983, 10.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(33.3665, 1.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(32.9742, 1.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(32.9742, -1.0000, 0)
	S007 = Part.LineSegment(P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_vaxis_holderB2_faceOuter_Fa0():
	FC000 = ctr_face_vaxis_holderB2_faceOuter_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def vaxis_holderB2_faceOuter():
	FA000 = face_vaxis_holderB2_faceOuter_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_vaxis_holderB2_faceButtress1_Fa0_Ctr0():
	P000 = App.Vector(29.0000, -1.0000, 0)
	P001 = App.Vector(33.4483, -1.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(33.8165, -10.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(29.0000, -1.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_vaxis_holderB2_faceButtress1_Fa0():
	FC000 = ctr_face_vaxis_holderB2_faceButtress1_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def vaxis_holderB2_faceButtress1():
	FA000 = face_vaxis_holderB2_faceButtress1_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_vaxis_holderB2_faceButtress2_Fa0_Ctr0():
	P000 = App.Vector(29.0000, 1.0000, 0)
	P001 = App.Vector(33.3665, 1.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(32.9983, 10.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(29.0000, 7.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(29.0000, 1.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_vaxis_holderB2_faceButtress2_Fa0():
	FC000 = ctr_face_vaxis_holderB2_faceButtress2_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def vaxis_holderB2_faceButtress2():
	FA000 = face_vaxis_holderB2_faceButtress2_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_vaxis_holderB2_outer():
	FIG = vaxis_holderB2_faceOuter()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_vaxis_holderB2_outer = fex_subpax_vaxis_holderB2_outer()

def fex_subpax_vaxis_holderB2_petal():
	FIG = vaxis_holderB2_facePetal()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, -1.0000))
	return VFP
subpax_vaxis_holderB2_petal = fex_subpax_vaxis_holderB2_petal()

def fex_subpax_vaxis_holderB2_b1_0():
	FIG = vaxis_holderB2_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 1.0000, 0.0000))
	return VFP
subpax_vaxis_holderB2_b1_0 = fex_subpax_vaxis_holderB2_b1_0()

def fex_subpax_vaxis_holderB2_b1_1():
	FIG = vaxis_holderB2_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 60.0000)
	VFP = VR3.translate(App.Vector(-0.8660, 0.5000, 0.0000))
	return VFP
subpax_vaxis_holderB2_b1_1 = fex_subpax_vaxis_holderB2_b1_1()

def fex_subpax_vaxis_holderB2_b1_2():
	FIG = vaxis_holderB2_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 120.0000)
	VFP = VR3.translate(App.Vector(-0.8660, -0.5000, 0.0000))
	return VFP
subpax_vaxis_holderB2_b1_2 = fex_subpax_vaxis_holderB2_b1_2()

def fex_subpax_vaxis_holderB2_b1_3():
	FIG = vaxis_holderB2_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 180.0000)
	VFP = VR3.translate(App.Vector(-0.0000, -1.0000, 0.0000))
	return VFP
subpax_vaxis_holderB2_b1_3 = fex_subpax_vaxis_holderB2_b1_3()

def fex_subpax_vaxis_holderB2_b1_4():
	FIG = vaxis_holderB2_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -120.0000)
	VFP = VR3.translate(App.Vector(0.8660, -0.5000, 0.0000))
	return VFP
subpax_vaxis_holderB2_b1_4 = fex_subpax_vaxis_holderB2_b1_4()

def fex_subpax_vaxis_holderB2_b1_5():
	FIG = vaxis_holderB2_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -60.0000)
	VFP = VR3.translate(App.Vector(0.8660, 0.5000, 0.0000))
	return VFP
subpax_vaxis_holderB2_b1_5 = fex_subpax_vaxis_holderB2_b1_5()

def fex_subpax_vaxis_holderB2_b2_0():
	FIG = vaxis_holderB2_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 1.0000, 0.0000))
	return VFP
subpax_vaxis_holderB2_b2_0 = fex_subpax_vaxis_holderB2_b2_0()

def fex_subpax_vaxis_holderB2_b2_1():
	FIG = vaxis_holderB2_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 60.0000)
	VFP = VR3.translate(App.Vector(-0.8660, 0.5000, 0.0000))
	return VFP
subpax_vaxis_holderB2_b2_1 = fex_subpax_vaxis_holderB2_b2_1()

def fex_subpax_vaxis_holderB2_b2_2():
	FIG = vaxis_holderB2_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 120.0000)
	VFP = VR3.translate(App.Vector(-0.8660, -0.5000, 0.0000))
	return VFP
subpax_vaxis_holderB2_b2_2 = fex_subpax_vaxis_holderB2_b2_2()

def fex_subpax_vaxis_holderB2_b2_3():
	FIG = vaxis_holderB2_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 180.0000)
	VFP = VR3.translate(App.Vector(-0.0000, -1.0000, 0.0000))
	return VFP
subpax_vaxis_holderB2_b2_3 = fex_subpax_vaxis_holderB2_b2_3()

def fex_subpax_vaxis_holderB2_b2_4():
	FIG = vaxis_holderB2_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -120.0000)
	VFP = VR3.translate(App.Vector(0.8660, -0.5000, 0.0000))
	return VFP
subpax_vaxis_holderB2_b2_4 = fex_subpax_vaxis_holderB2_b2_4()

def fex_subpax_vaxis_holderB2_b2_5():
	FIG = vaxis_holderB2_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -60.0000)
	VFP = VR3.translate(App.Vector(0.8660, 0.5000, 0.0000))
	return VFP
subpax_vaxis_holderB2_b2_5 = fex_subpax_vaxis_holderB2_b2_5()

pax_vaxis_holderB2 = subpax_vaxis_holderB2_petal.fuse([subpax_vaxis_holderB2_outer, subpax_vaxis_holderB2_b1_0, subpax_vaxis_holderB2_b1_1, subpax_vaxis_holderB2_b1_2, subpax_vaxis_holderB2_b1_3, subpax_vaxis_holderB2_b1_4, subpax_vaxis_holderB2_b1_5, subpax_vaxis_holderB2_b2_0, subpax_vaxis_holderB2_b2_1, subpax_vaxis_holderB2_b2_2, subpax_vaxis_holderB2_b2_3, subpax_vaxis_holderB2_b2_4, subpax_vaxis_holderB2_b2_5])
def ctr_face_vaxis_holderB1_facePetal_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(39.9120, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holderB1_facePetal_Fa0_Ctr1():
	P000 = App.Vector(34.1305, -4.0294, 0)
	P001 = App.Vector(26.4710, -1.9288, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(25.0000, 0.0000, 0)
	P003 = App.Vector(26.4710, 1.9288, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(34.1305, 4.0294, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(36.5147, 5.8493, 0)
	P006 = App.Vector(36.9635, 8.8148, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(32.9090, 19.0000, 0)
	P008 = App.Vector(26.1156, 27.6039, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(23.3229, 28.6980, 0)
	P010 = App.Vector(20.5548, 27.5432, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(14.9059, 21.9602, 0)
	S006 = Part.LineSegment(P010, P011)
	P012 = App.Vector(12.5000, 21.6506, 0)
	P013 = App.Vector(11.5651, 23.8890, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(13.5757, 31.5726, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(13.1917, 34.5473, 0)
	P016 = App.Vector(10.8479, 36.4187, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(-0.0000, 38.0000, 0)
	P018 = App.Vector(-10.8479, 36.4187, 0)
	S010 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-13.1917, 34.5473, 0)
	P020 = App.Vector(-13.5757, 31.5726, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(-11.5651, 23.8890, 0)
	S012 = Part.LineSegment(P020, P021)
	P022 = App.Vector(-12.5000, 21.6506, 0)
	P023 = App.Vector(-14.9059, 21.9602, 0)
	S013 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(-20.5548, 27.5432, 0)
	S014 = Part.LineSegment(P023, P024)
	P025 = App.Vector(-23.3229, 28.6980, 0)
	P026 = App.Vector(-26.1156, 27.6039, 0)
	S015 = Part.Arc(P024, P025, P026)
	P027 = App.Vector(-32.9090, 19.0000, 0)
	P028 = App.Vector(-36.9635, 8.8148, 0)
	S016 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-36.5147, 5.8493, 0)
	P030 = App.Vector(-34.1305, 4.0294, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-26.4710, 1.9288, 0)
	S018 = Part.LineSegment(P030, P031)
	P032 = App.Vector(-25.0000, 0.0000, 0)
	P033 = App.Vector(-26.4710, -1.9288, 0)
	S019 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-34.1305, -4.0294, 0)
	S020 = Part.LineSegment(P033, P034)
	P035 = App.Vector(-36.5147, -5.8493, 0)
	P036 = App.Vector(-36.9635, -8.8148, 0)
	S021 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-32.9090, -19.0000, 0)
	P038 = App.Vector(-26.1156, -27.6039, 0)
	S022 = Part.Arc(P036, P037, P038)
	P039 = App.Vector(-23.3229, -28.6980, 0)
	P040 = App.Vector(-20.5548, -27.5432, 0)
	S023 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-14.9059, -21.9602, 0)
	S024 = Part.LineSegment(P040, P041)
	P042 = App.Vector(-12.5000, -21.6506, 0)
	P043 = App.Vector(-11.5651, -23.8890, 0)
	S025 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(-13.5757, -31.5726, 0)
	S026 = Part.LineSegment(P043, P044)
	P045 = App.Vector(-13.1917, -34.5473, 0)
	P046 = App.Vector(-10.8479, -36.4187, 0)
	S027 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(0.0000, -38.0000, 0)
	P048 = App.Vector(10.8479, -36.4187, 0)
	S028 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(13.1917, -34.5473, 0)
	P050 = App.Vector(13.5757, -31.5726, 0)
	S029 = Part.Arc(P048, P049, P050)
	P051 = App.Vector(11.5651, -23.8890, 0)
	S030 = Part.LineSegment(P050, P051)
	P052 = App.Vector(12.5000, -21.6506, 0)
	P053 = App.Vector(14.9059, -21.9602, 0)
	S031 = Part.Arc(P051, P052, P053)
	P054 = App.Vector(20.5548, -27.5432, 0)
	S032 = Part.LineSegment(P053, P054)
	P055 = App.Vector(23.3229, -28.6980, 0)
	P056 = App.Vector(26.1156, -27.6039, 0)
	S033 = Part.Arc(P054, P055, P056)
	P057 = App.Vector(32.9090, -19.0000, 0)
	P058 = App.Vector(36.9635, -8.8148, 0)
	S034 = Part.Arc(P056, P057, P058)
	P059 = App.Vector(36.5147, -5.8493, 0)
	P060 = App.Vector(34.1305, -4.0294, 0)
	S035 = Part.Arc(P058, P059, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_vaxis_holderB1_facePetal_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(27.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holderB1_facePetal_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(13.5000, 23.3827, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holderB1_facePetal_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-13.5000, 23.3827, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holderB1_facePetal_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-27.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holderB1_facePetal_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-13.5000, -23.3827, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holderB1_facePetal_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(13.5000, -23.3827, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_vaxis_holderB1_facePetal_Fa0():
	FC000 = ctr_face_vaxis_holderB1_facePetal_Fa0_Ctr0()
	FC001 = ctr_face_vaxis_holderB1_facePetal_Fa0_Ctr1()
	FC002 = ctr_face_vaxis_holderB1_facePetal_Fa0_Ctr2()
	FC003 = ctr_face_vaxis_holderB1_facePetal_Fa0_Ctr3()
	FC004 = ctr_face_vaxis_holderB1_facePetal_Fa0_Ctr4()
	FC005 = ctr_face_vaxis_holderB1_facePetal_Fa0_Ctr5()
	FC006 = ctr_face_vaxis_holderB1_facePetal_Fa0_Ctr6()
	FC007 = ctr_face_vaxis_holderB1_facePetal_Fa0_Ctr7()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007])
	rOneFace.check()
	return rOneFace

def vaxis_holderB1_facePetal():
	FA000 = face_vaxis_holderB1_facePetal_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_vaxis_holderB1_faceOuter_Fa0_Ctr0():
	P000 = App.Vector(38.9969, -1.0000, 0)
	P001 = App.Vector(39.9938, -1.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(40.3620, -10.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(42.3603, -9.9183, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(41.5421, 10.0817, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(39.5438, 10.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(39.9120, 1.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(38.9969, 1.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(38.9969, -1.0000, 0)
	S007 = Part.LineSegment(P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_vaxis_holderB1_faceOuter_Fa0():
	FC000 = ctr_face_vaxis_holderB1_faceOuter_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def vaxis_holderB1_faceOuter():
	FA000 = face_vaxis_holderB1_faceOuter_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_vaxis_holderB1_faceButtress1_Fa0_Ctr0():
	P000 = App.Vector(29.0000, -1.0000, 0)
	P001 = App.Vector(39.9938, -1.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(40.3620, -10.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(29.0000, -1.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_vaxis_holderB1_faceButtress1_Fa0():
	FC000 = ctr_face_vaxis_holderB1_faceButtress1_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def vaxis_holderB1_faceButtress1():
	FA000 = face_vaxis_holderB1_faceButtress1_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_vaxis_holderB1_faceButtress2_Fa0_Ctr0():
	P000 = App.Vector(29.0000, 1.0000, 0)
	P001 = App.Vector(39.9120, 1.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(39.5438, 10.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(29.0000, 7.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(29.0000, 1.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_vaxis_holderB1_faceButtress2_Fa0():
	FC000 = ctr_face_vaxis_holderB1_faceButtress2_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def vaxis_holderB1_faceButtress2():
	FA000 = face_vaxis_holderB1_faceButtress2_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_vaxis_holderB1_outer():
	FIG = vaxis_holderB1_faceOuter()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_vaxis_holderB1_outer = fex_subpax_vaxis_holderB1_outer()

def fex_subpax_vaxis_holderB1_petal():
	FIG = vaxis_holderB1_facePetal()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, -1.0000))
	return VFP
subpax_vaxis_holderB1_petal = fex_subpax_vaxis_holderB1_petal()

def fex_subpax_vaxis_holderB1_b1_0():
	FIG = vaxis_holderB1_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 1.0000, 0.0000))
	return VFP
subpax_vaxis_holderB1_b1_0 = fex_subpax_vaxis_holderB1_b1_0()

def fex_subpax_vaxis_holderB1_b1_1():
	FIG = vaxis_holderB1_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 60.0000)
	VFP = VR3.translate(App.Vector(-0.8660, 0.5000, 0.0000))
	return VFP
subpax_vaxis_holderB1_b1_1 = fex_subpax_vaxis_holderB1_b1_1()

def fex_subpax_vaxis_holderB1_b1_2():
	FIG = vaxis_holderB1_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 120.0000)
	VFP = VR3.translate(App.Vector(-0.8660, -0.5000, 0.0000))
	return VFP
subpax_vaxis_holderB1_b1_2 = fex_subpax_vaxis_holderB1_b1_2()

def fex_subpax_vaxis_holderB1_b1_3():
	FIG = vaxis_holderB1_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 180.0000)
	VFP = VR3.translate(App.Vector(-0.0000, -1.0000, 0.0000))
	return VFP
subpax_vaxis_holderB1_b1_3 = fex_subpax_vaxis_holderB1_b1_3()

def fex_subpax_vaxis_holderB1_b1_4():
	FIG = vaxis_holderB1_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -120.0000)
	VFP = VR3.translate(App.Vector(0.8660, -0.5000, 0.0000))
	return VFP
subpax_vaxis_holderB1_b1_4 = fex_subpax_vaxis_holderB1_b1_4()

def fex_subpax_vaxis_holderB1_b1_5():
	FIG = vaxis_holderB1_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -60.0000)
	VFP = VR3.translate(App.Vector(0.8660, 0.5000, 0.0000))
	return VFP
subpax_vaxis_holderB1_b1_5 = fex_subpax_vaxis_holderB1_b1_5()

def fex_subpax_vaxis_holderB1_b2_0():
	FIG = vaxis_holderB1_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 1.0000, 0.0000))
	return VFP
subpax_vaxis_holderB1_b2_0 = fex_subpax_vaxis_holderB1_b2_0()

def fex_subpax_vaxis_holderB1_b2_1():
	FIG = vaxis_holderB1_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 60.0000)
	VFP = VR3.translate(App.Vector(-0.8660, 0.5000, 0.0000))
	return VFP
subpax_vaxis_holderB1_b2_1 = fex_subpax_vaxis_holderB1_b2_1()

def fex_subpax_vaxis_holderB1_b2_2():
	FIG = vaxis_holderB1_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 120.0000)
	VFP = VR3.translate(App.Vector(-0.8660, -0.5000, 0.0000))
	return VFP
subpax_vaxis_holderB1_b2_2 = fex_subpax_vaxis_holderB1_b2_2()

def fex_subpax_vaxis_holderB1_b2_3():
	FIG = vaxis_holderB1_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 180.0000)
	VFP = VR3.translate(App.Vector(-0.0000, -1.0000, 0.0000))
	return VFP
subpax_vaxis_holderB1_b2_3 = fex_subpax_vaxis_holderB1_b2_3()

def fex_subpax_vaxis_holderB1_b2_4():
	FIG = vaxis_holderB1_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -120.0000)
	VFP = VR3.translate(App.Vector(0.8660, -0.5000, 0.0000))
	return VFP
subpax_vaxis_holderB1_b2_4 = fex_subpax_vaxis_holderB1_b2_4()

def fex_subpax_vaxis_holderB1_b2_5():
	FIG = vaxis_holderB1_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -60.0000)
	VFP = VR3.translate(App.Vector(0.8660, 0.5000, 0.0000))
	return VFP
subpax_vaxis_holderB1_b2_5 = fex_subpax_vaxis_holderB1_b2_5()

pax_vaxis_holderB1 = subpax_vaxis_holderB1_petal.fuse([subpax_vaxis_holderB1_outer, subpax_vaxis_holderB1_b1_0, subpax_vaxis_holderB1_b1_1, subpax_vaxis_holderB1_b1_2, subpax_vaxis_holderB1_b1_3, subpax_vaxis_holderB1_b1_4, subpax_vaxis_holderB1_b1_5, subpax_vaxis_holderB1_b2_0, subpax_vaxis_holderB1_b2_1, subpax_vaxis_holderB1_b2_2, subpax_vaxis_holderB1_b2_3, subpax_vaxis_holderB1_b2_4, subpax_vaxis_holderB1_b2_5])
def ctr_face_vaxis_holderA_facePetal_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(41.5483, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holderA_facePetal_Fa0_Ctr1():
	P000 = App.Vector(36.5875, -3.8447, 0)
	P001 = App.Vector(31.3013, -1.8740, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(30.0000, 0.0000, 0)
	P003 = App.Vector(31.3013, 1.8740, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(36.5875, 3.8447, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(38.6991, 5.6725, 0)
	P006 = App.Vector(39.1002, 8.4364, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(34.6410, 20.0000, 0)
	P008 = App.Vector(26.8562, 29.6436, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(24.2621, 30.6782, 0)
	P010 = App.Vector(21.6234, 29.7633, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(17.2736, 26.1708, 0)
	S006 = Part.LineSegment(P010, P011)
	P012 = App.Vector(15.0000, 25.9808, 0)
	P013 = App.Vector(14.0277, 28.0448, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(14.9641, 33.6081, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(14.4370, 36.3507, 0)
	P016 = App.Vector(12.2440, 38.0800, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(-0.0000, 40.0000, 0)
	P018 = App.Vector(-12.2440, 38.0800, 0)
	S010 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-14.4370, 36.3507, 0)
	P020 = App.Vector(-14.9641, 33.6081, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(-14.0277, 28.0448, 0)
	S012 = Part.LineSegment(P020, P021)
	P022 = App.Vector(-15.0000, 25.9808, 0)
	P023 = App.Vector(-17.2736, 26.1708, 0)
	S013 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(-21.6234, 29.7633, 0)
	S014 = Part.LineSegment(P023, P024)
	P025 = App.Vector(-24.2621, 30.6782, 0)
	P026 = App.Vector(-26.8562, 29.6436, 0)
	S015 = Part.Arc(P024, P025, P026)
	P027 = App.Vector(-34.6410, 20.0000, 0)
	P028 = App.Vector(-39.1002, 8.4364, 0)
	S016 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-38.6991, 5.6725, 0)
	P030 = App.Vector(-36.5875, 3.8447, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-31.3013, 1.8740, 0)
	S018 = Part.LineSegment(P030, P031)
	P032 = App.Vector(-30.0000, 0.0000, 0)
	P033 = App.Vector(-31.3013, -1.8740, 0)
	S019 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-36.5875, -3.8447, 0)
	S020 = Part.LineSegment(P033, P034)
	P035 = App.Vector(-38.6991, -5.6725, 0)
	P036 = App.Vector(-39.1002, -8.4364, 0)
	S021 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-34.6410, -20.0000, 0)
	P038 = App.Vector(-26.8562, -29.6436, 0)
	S022 = Part.Arc(P036, P037, P038)
	P039 = App.Vector(-24.2621, -30.6782, 0)
	P040 = App.Vector(-21.6234, -29.7633, 0)
	S023 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-17.2736, -26.1708, 0)
	S024 = Part.LineSegment(P040, P041)
	P042 = App.Vector(-15.0000, -25.9808, 0)
	P043 = App.Vector(-14.0277, -28.0448, 0)
	S025 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(-14.9641, -33.6081, 0)
	S026 = Part.LineSegment(P043, P044)
	P045 = App.Vector(-14.4370, -36.3507, 0)
	P046 = App.Vector(-12.2440, -38.0800, 0)
	S027 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(-0.0000, -40.0000, 0)
	P048 = App.Vector(12.2440, -38.0800, 0)
	S028 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(14.4370, -36.3507, 0)
	P050 = App.Vector(14.9641, -33.6081, 0)
	S029 = Part.Arc(P048, P049, P050)
	P051 = App.Vector(14.0277, -28.0448, 0)
	S030 = Part.LineSegment(P050, P051)
	P052 = App.Vector(15.0000, -25.9808, 0)
	P053 = App.Vector(17.2736, -26.1708, 0)
	S031 = Part.Arc(P051, P052, P053)
	P054 = App.Vector(21.6234, -29.7633, 0)
	S032 = Part.LineSegment(P053, P054)
	P055 = App.Vector(24.2621, -30.6782, 0)
	P056 = App.Vector(26.8562, -29.6436, 0)
	S033 = Part.Arc(P054, P055, P056)
	P057 = App.Vector(34.6410, -20.0000, 0)
	P058 = App.Vector(39.1002, -8.4364, 0)
	S034 = Part.Arc(P056, P057, P058)
	P059 = App.Vector(38.6991, -5.6725, 0)
	P060 = App.Vector(36.5875, -3.8447, 0)
	S035 = Part.Arc(P058, P059, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_vaxis_holderA_facePetal_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(32.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holderA_facePetal_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(16.0000, 27.7128, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holderA_facePetal_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-16.0000, 27.7128, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holderA_facePetal_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-32.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holderA_facePetal_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-16.0000, -27.7128, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holderA_facePetal_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(16.0000, -27.7128, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_vaxis_holderA_facePetal_Fa0():
	FC000 = ctr_face_vaxis_holderA_facePetal_Fa0_Ctr0()
	FC001 = ctr_face_vaxis_holderA_facePetal_Fa0_Ctr1()
	FC002 = ctr_face_vaxis_holderA_facePetal_Fa0_Ctr2()
	FC003 = ctr_face_vaxis_holderA_facePetal_Fa0_Ctr3()
	FC004 = ctr_face_vaxis_holderA_facePetal_Fa0_Ctr4()
	FC005 = ctr_face_vaxis_holderA_facePetal_Fa0_Ctr5()
	FC006 = ctr_face_vaxis_holderA_facePetal_Fa0_Ctr6()
	FC007 = ctr_face_vaxis_holderA_facePetal_Fa0_Ctr7()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007])
	rOneFace.check()
	return rOneFace

def vaxis_holderA_facePetal():
	FA000 = face_vaxis_holderA_facePetal_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_vaxis_holderA_faceOuter_Fa0_Ctr0():
	P000 = App.Vector(40.8151, -1.0000, 0)
	P001 = App.Vector(41.6301, -1.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(41.9983, -10.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(43.9967, -9.9183, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(43.1785, 10.0817, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(41.1801, 10.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(41.5483, 1.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(40.8151, 1.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(40.8151, -1.0000, 0)
	S007 = Part.LineSegment(P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_vaxis_holderA_faceOuter_Fa0():
	FC000 = ctr_face_vaxis_holderA_faceOuter_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def vaxis_holderA_faceOuter():
	FA000 = face_vaxis_holderA_faceOuter_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_vaxis_holderA_faceButtress1_Fa0_Ctr0():
	P000 = App.Vector(34.0000, -1.0000, 0)
	P001 = App.Vector(41.6301, -1.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(41.9983, -10.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(34.0000, -1.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_vaxis_holderA_faceButtress1_Fa0():
	FC000 = ctr_face_vaxis_holderA_faceButtress1_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def vaxis_holderA_faceButtress1():
	FA000 = face_vaxis_holderA_faceButtress1_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_vaxis_holderA_faceButtress2_Fa0_Ctr0():
	P000 = App.Vector(34.0000, 1.0000, 0)
	P001 = App.Vector(41.5483, 1.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(41.1801, 10.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(34.0000, 7.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(34.0000, 1.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_vaxis_holderA_faceButtress2_Fa0():
	FC000 = ctr_face_vaxis_holderA_faceButtress2_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def vaxis_holderA_faceButtress2():
	FA000 = face_vaxis_holderA_faceButtress2_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_vaxis_holderA_outer():
	FIG = vaxis_holderA_faceOuter()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_vaxis_holderA_outer = fex_subpax_vaxis_holderA_outer()

def fex_subpax_vaxis_holderA_petal():
	FIG = vaxis_holderA_facePetal()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, -1.0000))
	return VFP
subpax_vaxis_holderA_petal = fex_subpax_vaxis_holderA_petal()

def fex_subpax_vaxis_holderA_b1_0():
	FIG = vaxis_holderA_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 1.0000, 0.0000))
	return VFP
subpax_vaxis_holderA_b1_0 = fex_subpax_vaxis_holderA_b1_0()

def fex_subpax_vaxis_holderA_b1_1():
	FIG = vaxis_holderA_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 60.0000)
	VFP = VR3.translate(App.Vector(-0.8660, 0.5000, 0.0000))
	return VFP
subpax_vaxis_holderA_b1_1 = fex_subpax_vaxis_holderA_b1_1()

def fex_subpax_vaxis_holderA_b1_2():
	FIG = vaxis_holderA_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 120.0000)
	VFP = VR3.translate(App.Vector(-0.8660, -0.5000, 0.0000))
	return VFP
subpax_vaxis_holderA_b1_2 = fex_subpax_vaxis_holderA_b1_2()

def fex_subpax_vaxis_holderA_b1_3():
	FIG = vaxis_holderA_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 180.0000)
	VFP = VR3.translate(App.Vector(-0.0000, -1.0000, 0.0000))
	return VFP
subpax_vaxis_holderA_b1_3 = fex_subpax_vaxis_holderA_b1_3()

def fex_subpax_vaxis_holderA_b1_4():
	FIG = vaxis_holderA_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -120.0000)
	VFP = VR3.translate(App.Vector(0.8660, -0.5000, 0.0000))
	return VFP
subpax_vaxis_holderA_b1_4 = fex_subpax_vaxis_holderA_b1_4()

def fex_subpax_vaxis_holderA_b1_5():
	FIG = vaxis_holderA_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -60.0000)
	VFP = VR3.translate(App.Vector(0.8660, 0.5000, 0.0000))
	return VFP
subpax_vaxis_holderA_b1_5 = fex_subpax_vaxis_holderA_b1_5()

def fex_subpax_vaxis_holderA_b2_0():
	FIG = vaxis_holderA_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 1.0000, 0.0000))
	return VFP
subpax_vaxis_holderA_b2_0 = fex_subpax_vaxis_holderA_b2_0()

def fex_subpax_vaxis_holderA_b2_1():
	FIG = vaxis_holderA_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 60.0000)
	VFP = VR3.translate(App.Vector(-0.8660, 0.5000, 0.0000))
	return VFP
subpax_vaxis_holderA_b2_1 = fex_subpax_vaxis_holderA_b2_1()

def fex_subpax_vaxis_holderA_b2_2():
	FIG = vaxis_holderA_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 120.0000)
	VFP = VR3.translate(App.Vector(-0.8660, -0.5000, 0.0000))
	return VFP
subpax_vaxis_holderA_b2_2 = fex_subpax_vaxis_holderA_b2_2()

def fex_subpax_vaxis_holderA_b2_3():
	FIG = vaxis_holderA_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 180.0000)
	VFP = VR3.translate(App.Vector(-0.0000, -1.0000, 0.0000))
	return VFP
subpax_vaxis_holderA_b2_3 = fex_subpax_vaxis_holderA_b2_3()

def fex_subpax_vaxis_holderA_b2_4():
	FIG = vaxis_holderA_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -120.0000)
	VFP = VR3.translate(App.Vector(0.8660, -0.5000, 0.0000))
	return VFP
subpax_vaxis_holderA_b2_4 = fex_subpax_vaxis_holderA_b2_4()

def fex_subpax_vaxis_holderA_b2_5():
	FIG = vaxis_holderA_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -60.0000)
	VFP = VR3.translate(App.Vector(0.8660, 0.5000, 0.0000))
	return VFP
subpax_vaxis_holderA_b2_5 = fex_subpax_vaxis_holderA_b2_5()

pax_vaxis_holderA = subpax_vaxis_holderA_petal.fuse([subpax_vaxis_holderA_outer, subpax_vaxis_holderA_b1_0, subpax_vaxis_holderA_b1_1, subpax_vaxis_holderA_b1_2, subpax_vaxis_holderA_b1_3, subpax_vaxis_holderA_b1_4, subpax_vaxis_holderA_b1_5, subpax_vaxis_holderA_b2_0, subpax_vaxis_holderA_b2_1, subpax_vaxis_holderA_b2_2, subpax_vaxis_holderA_b2_3, subpax_vaxis_holderA_b2_4, subpax_vaxis_holderA_b2_5])
def finh_inpax_pole_static_hB2():
	IVR1 = pax_vaxis_holderB2.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	IVR2 = IVR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	IVR3 = IVR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	IVF = IVR3.translate(App.Vector(0.0000, 0.0000, 290.0000))
	return IVF
inpax_pole_static_hB2 = finh_inpax_pole_static_hB2()

def finh_inpax_pole_static_hB1():
	IVR1 = pax_vaxis_holderB1.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	IVR2 = IVR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	IVR3 = IVR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	IVF = IVR3.translate(App.Vector(0.0000, 0.0000, 130.0000))
	return IVF
inpax_pole_static_hB1 = finh_inpax_pole_static_hB1()

def finh_inpax_pole_static_hA():
	IVR1 = pax_vaxis_holderA.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	IVR2 = IVR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	IVR3 = IVR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	IVF = IVR3.translate(App.Vector(0.0000, 0.0000, 90.0000))
	return IVF
inpax_pole_static_hA = finh_inpax_pole_static_hA()

def fex_subpax_pole_static_pole():
	FIG = pole_static_poleCut()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_pole_static_pole = fex_subpax_pole_static_pole()

def fex_subpax_pole_static_bottom():
	FIG = pole_static_poleBottom()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_pole_static_bottom = fex_subpax_pole_static_bottom()

def fex_subpax_pole_static_door():
	FIG = pole_static_poleFace()
	VEX = FIG.extrude(App.Vector(0, 0, 47))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_pole_static_door = fex_subpax_pole_static_door()

def fex_subpax_pole_static_emptyPole():
	FIG = pole_static_emptyPole()
	VEX = FIG.extrude(App.Vector(0, 0, 80))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_pole_static_emptyPole = fex_subpax_pole_static_emptyPole()

def fex_subpax_pole_static_emptyDoor():
	FIG = pole_static_emptyDoor()
	VEX = FIG.extrude(App.Vector(0, 0, 57))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_pole_static_emptyDoor = fex_subpax_pole_static_emptyDoor()

ipax_pole_static_door = subpax_pole_static_door.common([subpax_pole_static_emptyPole])
ipax_pole_static_pole = subpax_pole_static_pole.cut([subpax_pole_static_emptyDoor])
pax_pole_static = ipax_pole_static_pole.fuse([subpax_pole_static_bottom, ipax_pole_static_door, inpax_pole_static_hB2, inpax_pole_static_hB1, inpax_pole_static_hA])

pax_pole_static.check()
#pax_pole_static.exportBrep(f"{outFileName}.brep")
#pax_pole_static.exportIges(f"{outFileName}.igs")
#pax_pole_static.exportStep(f"{outFileName}.stp")
pax_pole_static.exportStl(f"{outFileName}.stl")

