# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "ring_guidance"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_ring_guidance_faceTop_Fa0_Ctr0():
	P000 = App.Vector(27.9800, -3.3068, 0)
	P001 = App.Vector(32.5796, -1.9142, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(34.0000, -0.0000, 0)
	P003 = App.Vector(32.5796, 1.9142, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(27.9800, 3.3068, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(26.2356, 4.3839, 0)
	P006 = App.Vector(25.2539, 6.1838, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(22.5167, 13.0000, 0)
	P008 = App.Vector(17.9823, 18.7786, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(16.9144, 20.5287, 0)
	P010 = App.Vector(16.8538, 22.5780, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(17.9475, 27.2576, 0)
	S006 = Part.LineSegment(P010, P011)
	P012 = App.Vector(17.0000, 29.4449, 0)
	P013 = App.Vector(14.6320, 29.1718, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(11.1262, 25.8848, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(9.3212, 24.9126, 0)
	P016 = App.Vector(7.2716, 24.9624, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(0.0000, 26.0000, 0)
	P018 = App.Vector(-7.2716, 24.9624, 0)
	S010 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-9.3212, 24.9126, 0)
	P020 = App.Vector(-11.1262, 25.8848, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(-14.6320, 29.1718, 0)
	S012 = Part.LineSegment(P020, P021)
	P022 = App.Vector(-17.0000, 29.4449, 0)
	P023 = App.Vector(-17.9475, 27.2576, 0)
	S013 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(-16.8538, 22.5780, 0)
	S014 = Part.LineSegment(P023, P024)
	P025 = App.Vector(-16.9144, 20.5287, 0)
	P026 = App.Vector(-17.9823, 18.7786, 0)
	S015 = Part.Arc(P024, P025, P026)
	P027 = App.Vector(-22.5167, 13.0000, 0)
	P028 = App.Vector(-25.2539, 6.1838, 0)
	S016 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-26.2356, 4.3839, 0)
	P030 = App.Vector(-27.9800, 3.3068, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-32.5796, 1.9142, 0)
	S018 = Part.LineSegment(P030, P031)
	P032 = App.Vector(-34.0000, 0.0000, 0)
	P033 = App.Vector(-32.5796, -1.9142, 0)
	S019 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-27.9800, -3.3068, 0)
	S020 = Part.LineSegment(P033, P034)
	P035 = App.Vector(-26.2356, -4.3839, 0)
	P036 = App.Vector(-25.2539, -6.1838, 0)
	S021 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-22.5167, -13.0000, 0)
	P038 = App.Vector(-17.9823, -18.7786, 0)
	S022 = Part.Arc(P036, P037, P038)
	P039 = App.Vector(-16.9144, -20.5287, 0)
	P040 = App.Vector(-16.8538, -22.5780, 0)
	S023 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-17.9475, -27.2576, 0)
	S024 = Part.LineSegment(P040, P041)
	P042 = App.Vector(-17.0000, -29.4449, 0)
	P043 = App.Vector(-14.6320, -29.1718, 0)
	S025 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(-11.1262, -25.8848, 0)
	S026 = Part.LineSegment(P043, P044)
	P045 = App.Vector(-9.3212, -24.9126, 0)
	P046 = App.Vector(-7.2716, -24.9624, 0)
	S027 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(-0.0000, -26.0000, 0)
	P048 = App.Vector(7.2716, -24.9624, 0)
	S028 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(9.3212, -24.9126, 0)
	P050 = App.Vector(11.1262, -25.8848, 0)
	S029 = Part.Arc(P048, P049, P050)
	P051 = App.Vector(14.6320, -29.1718, 0)
	S030 = Part.LineSegment(P050, P051)
	P052 = App.Vector(17.0000, -29.4449, 0)
	P053 = App.Vector(17.9475, -27.2576, 0)
	S031 = Part.Arc(P051, P052, P053)
	P054 = App.Vector(16.8538, -22.5780, 0)
	S032 = Part.LineSegment(P053, P054)
	P055 = App.Vector(16.9144, -20.5287, 0)
	P056 = App.Vector(17.9823, -18.7786, 0)
	S033 = Part.Arc(P054, P055, P056)
	P057 = App.Vector(22.5167, -13.0000, 0)
	P058 = App.Vector(25.2539, -6.1838, 0)
	S034 = Part.Arc(P056, P057, P058)
	P059 = App.Vector(26.2356, -4.3839, 0)
	P060 = App.Vector(27.9800, -3.3068, 0)
	S035 = Part.Arc(P058, P059, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_ring_guidance_faceTop_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_guidance_faceTop_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.0000, App.Vector(18.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_guidance_faceTop_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.0000, App.Vector(12.7279, 12.7279, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_guidance_faceTop_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.0000, App.Vector(0.0000, 18.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_guidance_faceTop_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.0000, App.Vector(-12.7279, 12.7279, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_guidance_faceTop_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.0000, App.Vector(-18.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_guidance_faceTop_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.0000, App.Vector(-12.7279, -12.7279, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_guidance_faceTop_Fa0_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.0000, App.Vector(-0.0000, -18.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_guidance_faceTop_Fa0_Ctr9():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.0000, App.Vector(12.7279, -12.7279, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_guidance_faceTop_Fa0_Ctr10():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(32.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_guidance_faceTop_Fa0_Ctr11():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(16.0000, 27.7128, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_guidance_faceTop_Fa0_Ctr12():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-16.0000, 27.7128, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_guidance_faceTop_Fa0_Ctr13():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-32.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_guidance_faceTop_Fa0_Ctr14():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-16.0000, -27.7128, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_ring_guidance_faceTop_Fa0_Ctr15():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(16.0000, -27.7128, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_ring_guidance_faceTop_Fa0():
	FC000 = ctr_face_ring_guidance_faceTop_Fa0_Ctr0()
	FC001 = ctr_face_ring_guidance_faceTop_Fa0_Ctr1()
	FC002 = ctr_face_ring_guidance_faceTop_Fa0_Ctr2()
	FC003 = ctr_face_ring_guidance_faceTop_Fa0_Ctr3()
	FC004 = ctr_face_ring_guidance_faceTop_Fa0_Ctr4()
	FC005 = ctr_face_ring_guidance_faceTop_Fa0_Ctr5()
	FC006 = ctr_face_ring_guidance_faceTop_Fa0_Ctr6()
	FC007 = ctr_face_ring_guidance_faceTop_Fa0_Ctr7()
	FC008 = ctr_face_ring_guidance_faceTop_Fa0_Ctr8()
	FC009 = ctr_face_ring_guidance_faceTop_Fa0_Ctr9()
	FC010 = ctr_face_ring_guidance_faceTop_Fa0_Ctr10()
	FC011 = ctr_face_ring_guidance_faceTop_Fa0_Ctr11()
	FC012 = ctr_face_ring_guidance_faceTop_Fa0_Ctr12()
	FC013 = ctr_face_ring_guidance_faceTop_Fa0_Ctr13()
	FC014 = ctr_face_ring_guidance_faceTop_Fa0_Ctr14()
	FC015 = ctr_face_ring_guidance_faceTop_Fa0_Ctr15()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008, FC009, FC010, FC011, FC012, FC013, FC014, FC015])
	rOneFace.check()
	return rOneFace

def ring_guidance_faceTop():
	FA000 = face_ring_guidance_faceTop_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_ring_guidance_faceSection_Fa0_Ctr0():
	P000 = App.Vector(15.0000, 0.0000, 0)
	P001 = App.Vector(34.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(34.0000, 2.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(15.0000, 2.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(15.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_ring_guidance_faceSection_Fa0():
	FC000 = ctr_face_ring_guidance_faceSection_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_ring_guidance_faceSection_Fa1_Ctr0():
	P000 = App.Vector(-34.0000, 0.0000, 0)
	P001 = App.Vector(-15.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-15.0000, 2.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-34.0000, 2.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-34.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_ring_guidance_faceSection_Fa1():
	FC000 = ctr_face_ring_guidance_faceSection_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ring_guidance_faceSection():
	FA000 = face_ring_guidance_faceSection_Fa0()
	FA001 = face_ring_guidance_faceSection_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def fex_subpax_ring_guidance_top():
	FIG = ring_guidance_faceTop()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_ring_guidance_top = fex_subpax_ring_guidance_top()

pax_ring_guidance = subpax_ring_guidance_top

pax_ring_guidance.check()
#pax_ring_guidance.exportBrep(f"{outFileName}.brep")
#pax_ring_guidance.exportIges(f"{outFileName}.igs")
#pax_ring_guidance.exportStep(f"{outFileName}.stp")
pax_ring_guidance.exportStl(f"{outFileName}.stl")

