# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "surface"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_surface_faceSurface_Fa0_Ctr0():
	P000 = App.Vector(-204.0000, -181.0000, 0)
	P001 = App.Vector(-124.0000, -181.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-124.0000, -131.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-204.0000, -131.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-204.0000, -181.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa0():
	FC000 = ctr_face_surface_faceSurface_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa1_Ctr0():
	P000 = App.Vector(-204.0000, -129.0000, 0)
	P001 = App.Vector(-124.0000, -129.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-124.0000, -79.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-204.0000, -79.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-204.0000, -129.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa1():
	FC000 = ctr_face_surface_faceSurface_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa2_Ctr0():
	P000 = App.Vector(-204.0000, -77.0000, 0)
	P001 = App.Vector(-124.0000, -77.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-124.0000, -27.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-204.0000, -27.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-204.0000, -77.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa2():
	FC000 = ctr_face_surface_faceSurface_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa3_Ctr0():
	P000 = App.Vector(-204.0000, -25.0000, 0)
	P001 = App.Vector(-124.0000, -25.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-124.0000, 25.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-204.0000, 25.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-204.0000, -25.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa3():
	FC000 = ctr_face_surface_faceSurface_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa4_Ctr0():
	P000 = App.Vector(-204.0000, 27.0000, 0)
	P001 = App.Vector(-124.0000, 27.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-124.0000, 77.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-204.0000, 77.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-204.0000, 27.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa4():
	FC000 = ctr_face_surface_faceSurface_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa5_Ctr0():
	P000 = App.Vector(-204.0000, 79.0000, 0)
	P001 = App.Vector(-124.0000, 79.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-124.0000, 129.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-204.0000, 129.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-204.0000, 79.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa5():
	FC000 = ctr_face_surface_faceSurface_Fa5_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa6_Ctr0():
	P000 = App.Vector(-204.0000, 131.0000, 0)
	P001 = App.Vector(-124.0000, 131.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-124.0000, 181.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-204.0000, 181.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-204.0000, 131.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa6():
	FC000 = ctr_face_surface_faceSurface_Fa6_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa7_Ctr0():
	P000 = App.Vector(-122.0000, -181.0000, 0)
	P001 = App.Vector(-42.0000, -181.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-42.0000, -131.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-122.0000, -131.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-122.0000, -181.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa7():
	FC000 = ctr_face_surface_faceSurface_Fa7_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa8_Ctr0():
	P000 = App.Vector(-122.0000, -129.0000, 0)
	P001 = App.Vector(-42.0000, -129.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-42.0000, -79.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-122.0000, -79.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-122.0000, -129.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa8():
	FC000 = ctr_face_surface_faceSurface_Fa8_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa9_Ctr0():
	P000 = App.Vector(-122.0000, -77.0000, 0)
	P001 = App.Vector(-42.0000, -77.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-42.0000, -27.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-122.0000, -27.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-122.0000, -77.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa9():
	FC000 = ctr_face_surface_faceSurface_Fa9_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa10_Ctr0():
	P000 = App.Vector(-122.0000, -25.0000, 0)
	P001 = App.Vector(-42.0000, -25.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-42.0000, 25.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-122.0000, 25.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-122.0000, -25.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa10():
	FC000 = ctr_face_surface_faceSurface_Fa10_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa11_Ctr0():
	P000 = App.Vector(-122.0000, 27.0000, 0)
	P001 = App.Vector(-42.0000, 27.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-42.0000, 77.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-122.0000, 77.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-122.0000, 27.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa11():
	FC000 = ctr_face_surface_faceSurface_Fa11_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa12_Ctr0():
	P000 = App.Vector(-122.0000, 79.0000, 0)
	P001 = App.Vector(-42.0000, 79.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-42.0000, 129.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-122.0000, 129.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-122.0000, 79.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa12():
	FC000 = ctr_face_surface_faceSurface_Fa12_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa13_Ctr0():
	P000 = App.Vector(-122.0000, 131.0000, 0)
	P001 = App.Vector(-42.0000, 131.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-42.0000, 181.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-122.0000, 181.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-122.0000, 131.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa13():
	FC000 = ctr_face_surface_faceSurface_Fa13_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa14_Ctr0():
	P000 = App.Vector(-40.0000, -181.0000, 0)
	P001 = App.Vector(40.0000, -181.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(40.0000, -131.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-40.0000, -131.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-40.0000, -181.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa14():
	FC000 = ctr_face_surface_faceSurface_Fa14_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa15_Ctr0():
	P000 = App.Vector(-40.0000, -129.0000, 0)
	P001 = App.Vector(40.0000, -129.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(40.0000, -79.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-40.0000, -79.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-40.0000, -129.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa15():
	FC000 = ctr_face_surface_faceSurface_Fa15_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa16_Ctr0():
	P000 = App.Vector(-40.0000, -77.0000, 0)
	P001 = App.Vector(40.0000, -77.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(40.0000, -27.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-40.0000, -27.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-40.0000, -77.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa16():
	FC000 = ctr_face_surface_faceSurface_Fa16_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa17_Ctr0():
	P000 = App.Vector(-40.0000, -25.0000, 0)
	P001 = App.Vector(40.0000, -25.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(40.0000, 25.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-40.0000, 25.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-40.0000, -25.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa17():
	FC000 = ctr_face_surface_faceSurface_Fa17_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa18_Ctr0():
	P000 = App.Vector(-40.0000, 27.0000, 0)
	P001 = App.Vector(40.0000, 27.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(40.0000, 77.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-40.0000, 77.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-40.0000, 27.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa18():
	FC000 = ctr_face_surface_faceSurface_Fa18_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa19_Ctr0():
	P000 = App.Vector(-40.0000, 79.0000, 0)
	P001 = App.Vector(40.0000, 79.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(40.0000, 129.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-40.0000, 129.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-40.0000, 79.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa19():
	FC000 = ctr_face_surface_faceSurface_Fa19_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa20_Ctr0():
	P000 = App.Vector(-40.0000, 131.0000, 0)
	P001 = App.Vector(40.0000, 131.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(40.0000, 181.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-40.0000, 181.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-40.0000, 131.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa20():
	FC000 = ctr_face_surface_faceSurface_Fa20_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa21_Ctr0():
	P000 = App.Vector(42.0000, -181.0000, 0)
	P001 = App.Vector(122.0000, -181.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(122.0000, -131.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(42.0000, -131.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(42.0000, -181.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa21():
	FC000 = ctr_face_surface_faceSurface_Fa21_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa22_Ctr0():
	P000 = App.Vector(42.0000, -129.0000, 0)
	P001 = App.Vector(122.0000, -129.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(122.0000, -79.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(42.0000, -79.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(42.0000, -129.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa22():
	FC000 = ctr_face_surface_faceSurface_Fa22_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa23_Ctr0():
	P000 = App.Vector(42.0000, -77.0000, 0)
	P001 = App.Vector(122.0000, -77.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(122.0000, -27.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(42.0000, -27.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(42.0000, -77.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa23():
	FC000 = ctr_face_surface_faceSurface_Fa23_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa24_Ctr0():
	P000 = App.Vector(42.0000, -25.0000, 0)
	P001 = App.Vector(122.0000, -25.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(122.0000, 25.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(42.0000, 25.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(42.0000, -25.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa24():
	FC000 = ctr_face_surface_faceSurface_Fa24_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa25_Ctr0():
	P000 = App.Vector(42.0000, 27.0000, 0)
	P001 = App.Vector(122.0000, 27.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(122.0000, 77.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(42.0000, 77.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(42.0000, 27.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa25():
	FC000 = ctr_face_surface_faceSurface_Fa25_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa26_Ctr0():
	P000 = App.Vector(42.0000, 79.0000, 0)
	P001 = App.Vector(122.0000, 79.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(122.0000, 129.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(42.0000, 129.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(42.0000, 79.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa26():
	FC000 = ctr_face_surface_faceSurface_Fa26_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa27_Ctr0():
	P000 = App.Vector(42.0000, 131.0000, 0)
	P001 = App.Vector(122.0000, 131.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(122.0000, 181.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(42.0000, 181.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(42.0000, 131.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa27():
	FC000 = ctr_face_surface_faceSurface_Fa27_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa28_Ctr0():
	P000 = App.Vector(124.0000, -181.0000, 0)
	P001 = App.Vector(204.0000, -181.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(204.0000, -131.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(124.0000, -131.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(124.0000, -181.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa28():
	FC000 = ctr_face_surface_faceSurface_Fa28_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa29_Ctr0():
	P000 = App.Vector(124.0000, -129.0000, 0)
	P001 = App.Vector(204.0000, -129.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(204.0000, -79.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(124.0000, -79.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(124.0000, -129.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa29():
	FC000 = ctr_face_surface_faceSurface_Fa29_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa30_Ctr0():
	P000 = App.Vector(124.0000, -77.0000, 0)
	P001 = App.Vector(204.0000, -77.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(204.0000, -27.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(124.0000, -27.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(124.0000, -77.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa30():
	FC000 = ctr_face_surface_faceSurface_Fa30_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa31_Ctr0():
	P000 = App.Vector(124.0000, -25.0000, 0)
	P001 = App.Vector(204.0000, -25.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(204.0000, 25.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(124.0000, 25.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(124.0000, -25.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa31():
	FC000 = ctr_face_surface_faceSurface_Fa31_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa32_Ctr0():
	P000 = App.Vector(124.0000, 27.0000, 0)
	P001 = App.Vector(204.0000, 27.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(204.0000, 77.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(124.0000, 77.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(124.0000, 27.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa32():
	FC000 = ctr_face_surface_faceSurface_Fa32_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa33_Ctr0():
	P000 = App.Vector(124.0000, 79.0000, 0)
	P001 = App.Vector(204.0000, 79.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(204.0000, 129.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(124.0000, 129.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(124.0000, 79.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa33():
	FC000 = ctr_face_surface_faceSurface_Fa33_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_surface_faceSurface_Fa34_Ctr0():
	P000 = App.Vector(124.0000, 131.0000, 0)
	P001 = App.Vector(204.0000, 131.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(204.0000, 181.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(124.0000, 181.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(124.0000, 131.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceSurface_Fa34():
	FC000 = ctr_face_surface_faceSurface_Fa34_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def surface_faceSurface():
	FA000 = face_surface_faceSurface_Fa0()
	FA001 = face_surface_faceSurface_Fa1()
	FA002 = face_surface_faceSurface_Fa2()
	FA003 = face_surface_faceSurface_Fa3()
	FA004 = face_surface_faceSurface_Fa4()
	FA005 = face_surface_faceSurface_Fa5()
	FA006 = face_surface_faceSurface_Fa6()
	FA007 = face_surface_faceSurface_Fa7()
	FA008 = face_surface_faceSurface_Fa8()
	FA009 = face_surface_faceSurface_Fa9()
	FA010 = face_surface_faceSurface_Fa10()
	FA011 = face_surface_faceSurface_Fa11()
	FA012 = face_surface_faceSurface_Fa12()
	FA013 = face_surface_faceSurface_Fa13()
	FA014 = face_surface_faceSurface_Fa14()
	FA015 = face_surface_faceSurface_Fa15()
	FA016 = face_surface_faceSurface_Fa16()
	FA017 = face_surface_faceSurface_Fa17()
	FA018 = face_surface_faceSurface_Fa18()
	FA019 = face_surface_faceSurface_Fa19()
	FA020 = face_surface_faceSurface_Fa20()
	FA021 = face_surface_faceSurface_Fa21()
	FA022 = face_surface_faceSurface_Fa22()
	FA023 = face_surface_faceSurface_Fa23()
	FA024 = face_surface_faceSurface_Fa24()
	FA025 = face_surface_faceSurface_Fa25()
	FA026 = face_surface_faceSurface_Fa26()
	FA027 = face_surface_faceSurface_Fa27()
	FA028 = face_surface_faceSurface_Fa28()
	FA029 = face_surface_faceSurface_Fa29()
	FA030 = face_surface_faceSurface_Fa30()
	FA031 = face_surface_faceSurface_Fa31()
	FA032 = face_surface_faceSurface_Fa32()
	FA033 = face_surface_faceSurface_Fa33()
	FA034 = face_surface_faceSurface_Fa34()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005, FA006, FA007, FA008, FA009, FA010, FA011, FA012, FA013, FA014, FA015, FA016, FA017, FA018, FA019, FA020, FA021, FA022, FA023, FA024, FA025, FA026, FA027, FA028, FA029, FA030, FA031, FA032, FA033, FA034])
	rOneFig.check()
	return rOneFig

def ctr_face_surface_faceOnePanel_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(80.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(80.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_surface_faceOnePanel_Fa0():
	FC000 = ctr_face_surface_faceOnePanel_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def surface_faceOnePanel():
	FA000 = face_surface_faceOnePanel_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_surface_panel_0():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(-204, -181, 0))
	return VFP
subpax_surface_panel_0 = fex_subpax_surface_panel_0()

def fex_subpax_surface_panel_1():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(-204, -129, 0))
	return VFP
subpax_surface_panel_1 = fex_subpax_surface_panel_1()

def fex_subpax_surface_panel_2():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(-204, -77, 0))
	return VFP
subpax_surface_panel_2 = fex_subpax_surface_panel_2()

def fex_subpax_surface_panel_3():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(-204, -25, 0))
	return VFP
subpax_surface_panel_3 = fex_subpax_surface_panel_3()

def fex_subpax_surface_panel_4():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(-204, 27, 0))
	return VFP
subpax_surface_panel_4 = fex_subpax_surface_panel_4()

def fex_subpax_surface_panel_5():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(-204, 79, 0))
	return VFP
subpax_surface_panel_5 = fex_subpax_surface_panel_5()

def fex_subpax_surface_panel_6():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(-204, 131, 0))
	return VFP
subpax_surface_panel_6 = fex_subpax_surface_panel_6()

def fex_subpax_surface_panel_7():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(-122, -181, 0))
	return VFP
subpax_surface_panel_7 = fex_subpax_surface_panel_7()

def fex_subpax_surface_panel_8():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(-122, -129, 0))
	return VFP
subpax_surface_panel_8 = fex_subpax_surface_panel_8()

def fex_subpax_surface_panel_9():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(-122, -77, 0))
	return VFP
subpax_surface_panel_9 = fex_subpax_surface_panel_9()

def fex_subpax_surface_panel_10():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(-122, -25, 0))
	return VFP
subpax_surface_panel_10 = fex_subpax_surface_panel_10()

def fex_subpax_surface_panel_11():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(-122, 27, 0))
	return VFP
subpax_surface_panel_11 = fex_subpax_surface_panel_11()

def fex_subpax_surface_panel_12():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(-122, 79, 0))
	return VFP
subpax_surface_panel_12 = fex_subpax_surface_panel_12()

def fex_subpax_surface_panel_13():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(-122, 131, 0))
	return VFP
subpax_surface_panel_13 = fex_subpax_surface_panel_13()

def fex_subpax_surface_panel_14():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(-40, -181, 0))
	return VFP
subpax_surface_panel_14 = fex_subpax_surface_panel_14()

def fex_subpax_surface_panel_15():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(-40, -129, 0))
	return VFP
subpax_surface_panel_15 = fex_subpax_surface_panel_15()

def fex_subpax_surface_panel_16():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(-40, -77, 0))
	return VFP
subpax_surface_panel_16 = fex_subpax_surface_panel_16()

def fex_subpax_surface_panel_17():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(-40, -25, 0))
	return VFP
subpax_surface_panel_17 = fex_subpax_surface_panel_17()

def fex_subpax_surface_panel_18():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(-40, 27, 0))
	return VFP
subpax_surface_panel_18 = fex_subpax_surface_panel_18()

def fex_subpax_surface_panel_19():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(-40, 79, 0))
	return VFP
subpax_surface_panel_19 = fex_subpax_surface_panel_19()

def fex_subpax_surface_panel_20():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(-40, 131, 0))
	return VFP
subpax_surface_panel_20 = fex_subpax_surface_panel_20()

def fex_subpax_surface_panel_21():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(42, -181, 0))
	return VFP
subpax_surface_panel_21 = fex_subpax_surface_panel_21()

def fex_subpax_surface_panel_22():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(42, -129, 0))
	return VFP
subpax_surface_panel_22 = fex_subpax_surface_panel_22()

def fex_subpax_surface_panel_23():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(42, -77, 0))
	return VFP
subpax_surface_panel_23 = fex_subpax_surface_panel_23()

def fex_subpax_surface_panel_24():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(42, -25, 0))
	return VFP
subpax_surface_panel_24 = fex_subpax_surface_panel_24()

def fex_subpax_surface_panel_25():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(42, 27, 0))
	return VFP
subpax_surface_panel_25 = fex_subpax_surface_panel_25()

def fex_subpax_surface_panel_26():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(42, 79, 0))
	return VFP
subpax_surface_panel_26 = fex_subpax_surface_panel_26()

def fex_subpax_surface_panel_27():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(42, 131, 0))
	return VFP
subpax_surface_panel_27 = fex_subpax_surface_panel_27()

def fex_subpax_surface_panel_28():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(124, -181, 0))
	return VFP
subpax_surface_panel_28 = fex_subpax_surface_panel_28()

def fex_subpax_surface_panel_29():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(124, -129, 0))
	return VFP
subpax_surface_panel_29 = fex_subpax_surface_panel_29()

def fex_subpax_surface_panel_30():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(124, -77, 0))
	return VFP
subpax_surface_panel_30 = fex_subpax_surface_panel_30()

def fex_subpax_surface_panel_31():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(124, -25, 0))
	return VFP
subpax_surface_panel_31 = fex_subpax_surface_panel_31()

def fex_subpax_surface_panel_32():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(124, 27, 0))
	return VFP
subpax_surface_panel_32 = fex_subpax_surface_panel_32()

def fex_subpax_surface_panel_33():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(124, 79, 0))
	return VFP
subpax_surface_panel_33 = fex_subpax_surface_panel_33()

def fex_subpax_surface_panel_34():
	FIG = surface_faceOnePanel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(124, 131, 0))
	return VFP
subpax_surface_panel_34 = fex_subpax_surface_panel_34()

pax_surface = subpax_surface_panel_0.fuse([subpax_surface_panel_1, subpax_surface_panel_2, subpax_surface_panel_3, subpax_surface_panel_4, subpax_surface_panel_5, subpax_surface_panel_6, subpax_surface_panel_7, subpax_surface_panel_8, subpax_surface_panel_9, subpax_surface_panel_10, subpax_surface_panel_11, subpax_surface_panel_12, subpax_surface_panel_13, subpax_surface_panel_14, subpax_surface_panel_15, subpax_surface_panel_16, subpax_surface_panel_17, subpax_surface_panel_18, subpax_surface_panel_19, subpax_surface_panel_20, subpax_surface_panel_21, subpax_surface_panel_22, subpax_surface_panel_23, subpax_surface_panel_24, subpax_surface_panel_25, subpax_surface_panel_26, subpax_surface_panel_27, subpax_surface_panel_28, subpax_surface_panel_29, subpax_surface_panel_30, subpax_surface_panel_31, subpax_surface_panel_32, subpax_surface_panel_33, subpax_surface_panel_34])

pax_surface.check()
#pax_surface.exportBrep(f"{outFileName}.brep")
#pax_surface.exportIges(f"{outFileName}.igs")
#pax_surface.exportStep(f"{outFileName}.stp")
pax_surface.exportStl(f"{outFileName}.stl")

