# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "rod"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_rod_faceCut_Fa0_Ctr0():
	P000 = App.Vector(4.0000, 0.0000, 0)
	P001 = App.Vector(4.0000, 12.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-4.0000, 12.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-4.0000, 0.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(4.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rod_faceCut_Fa0_Ctr1():
	P000 = App.Vector(2.0000, 2.0000, 0)
	P001 = App.Vector(2.0000, 10.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-2.0000, 10.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-2.0000, 2.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(2.0000, 2.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rod_faceCut_Fa0():
	FC000 = ctr_face_rod_faceCut_Fa0_Ctr0()
	FC001 = ctr_face_rod_faceCut_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def rod_faceCut():
	FA000 = face_rod_faceCut_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_rod_facePlate_Fa0_Ctr0():
	P000 = App.Vector(20.0000, 2.0000, 0)
	P001 = App.Vector(20.0000, 28.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(19.4142, 29.4142, 0)
	P003 = App.Vector(18.0000, 30.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-18.0000, 30.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-19.4142, 29.4142, 0)
	P006 = App.Vector(-20.0000, 28.0000, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-20.0000, 2.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-19.4142, 0.5858, 0)
	P009 = App.Vector(-18.0000, 0.0000, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(18.0000, 0.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(19.4142, 0.5858, 0)
	P012 = App.Vector(20.0000, 2.0000, 0)
	S007 = Part.Arc(P010, P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rod_facePlate_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(17.0000, 10.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_facePlate_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-17.0000, 10.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_facePlate_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(17.0000, 20.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_facePlate_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-17.0000, 20.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_facePlate_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-6.6667, 3.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_facePlate_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-6.6667, 27.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_facePlate_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(6.6667, 3.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_facePlate_Fa0_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(6.6667, 27.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rod_facePlate_Fa0():
	FC000 = ctr_face_rod_facePlate_Fa0_Ctr0()
	FC001 = ctr_face_rod_facePlate_Fa0_Ctr1()
	FC002 = ctr_face_rod_facePlate_Fa0_Ctr2()
	FC003 = ctr_face_rod_facePlate_Fa0_Ctr3()
	FC004 = ctr_face_rod_facePlate_Fa0_Ctr4()
	FC005 = ctr_face_rod_facePlate_Fa0_Ctr5()
	FC006 = ctr_face_rod_facePlate_Fa0_Ctr6()
	FC007 = ctr_face_rod_facePlate_Fa0_Ctr7()
	FC008 = ctr_face_rod_facePlate_Fa0_Ctr8()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008])
	rOneFace.check()
	return rOneFace

def rod_facePlate():
	FA000 = face_rod_facePlate_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_rod_faceTop_Fa0_Ctr0():
	P000 = App.Vector(20.0000, 2.0000, 0)
	P001 = App.Vector(20.0000, 28.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(19.4142, 29.4142, 0)
	P003 = App.Vector(18.0000, 30.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-18.0000, 30.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-19.4142, 29.4142, 0)
	P006 = App.Vector(-20.0000, 28.0000, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-20.0000, 2.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-19.4142, 0.5858, 0)
	P009 = App.Vector(-18.0000, 0.0000, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(18.0000, 0.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(19.4142, 0.5858, 0)
	P012 = App.Vector(20.0000, 2.0000, 0)
	S007 = Part.Arc(P010, P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rod_faceTop_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(17.0000, 10.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-17.0000, 10.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(17.0000, 20.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-17.0000, 20.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-6.6667, 3.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-6.6667, 27.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(6.6667, 3.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa0_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(6.6667, 27.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rod_faceTop_Fa0():
	FC000 = ctr_face_rod_faceTop_Fa0_Ctr0()
	FC001 = ctr_face_rod_faceTop_Fa0_Ctr1()
	FC002 = ctr_face_rod_faceTop_Fa0_Ctr2()
	FC003 = ctr_face_rod_faceTop_Fa0_Ctr3()
	FC004 = ctr_face_rod_faceTop_Fa0_Ctr4()
	FC005 = ctr_face_rod_faceTop_Fa0_Ctr5()
	FC006 = ctr_face_rod_faceTop_Fa0_Ctr6()
	FC007 = ctr_face_rod_faceTop_Fa0_Ctr7()
	FC008 = ctr_face_rod_faceTop_Fa0_Ctr8()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008])
	rOneFace.check()
	return rOneFace

def ctr_face_rod_faceTop_Fa1_Ctr0():
	P000 = App.Vector(20.0000, 54.6667, 0)
	P001 = App.Vector(20.0000, 80.6667, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(19.4142, 82.0809, 0)
	P003 = App.Vector(18.0000, 82.6667, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-18.0000, 82.6667, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-19.4142, 82.0809, 0)
	P006 = App.Vector(-20.0000, 80.6667, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-20.0000, 54.6667, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-19.4142, 53.2525, 0)
	P009 = App.Vector(-18.0000, 52.6667, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(18.0000, 52.6667, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(19.4142, 53.2525, 0)
	P012 = App.Vector(20.0000, 54.6667, 0)
	S007 = Part.Arc(P010, P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rod_faceTop_Fa1_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(17.0000, 62.6667, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa1_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-17.0000, 62.6667, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa1_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(17.0000, 72.6667, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa1_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-17.0000, 72.6667, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa1_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-6.6667, 55.6667, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa1_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-6.6667, 79.6667, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa1_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(6.6667, 55.6667, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa1_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(6.6667, 79.6667, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rod_faceTop_Fa1():
	FC000 = ctr_face_rod_faceTop_Fa1_Ctr0()
	FC001 = ctr_face_rod_faceTop_Fa1_Ctr1()
	FC002 = ctr_face_rod_faceTop_Fa1_Ctr2()
	FC003 = ctr_face_rod_faceTop_Fa1_Ctr3()
	FC004 = ctr_face_rod_faceTop_Fa1_Ctr4()
	FC005 = ctr_face_rod_faceTop_Fa1_Ctr5()
	FC006 = ctr_face_rod_faceTop_Fa1_Ctr6()
	FC007 = ctr_face_rod_faceTop_Fa1_Ctr7()
	FC008 = ctr_face_rod_faceTop_Fa1_Ctr8()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008])
	rOneFace.check()
	return rOneFace

def ctr_face_rod_faceTop_Fa2_Ctr0():
	P000 = App.Vector(20.0000, 107.3333, 0)
	P001 = App.Vector(20.0000, 133.3333, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(19.4142, 134.7475, 0)
	P003 = App.Vector(18.0000, 135.3333, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-18.0000, 135.3333, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-19.4142, 134.7475, 0)
	P006 = App.Vector(-20.0000, 133.3333, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-20.0000, 107.3333, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-19.4142, 105.9191, 0)
	P009 = App.Vector(-18.0000, 105.3333, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(18.0000, 105.3333, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(19.4142, 105.9191, 0)
	P012 = App.Vector(20.0000, 107.3333, 0)
	S007 = Part.Arc(P010, P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rod_faceTop_Fa2_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(17.0000, 115.3333, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa2_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-17.0000, 115.3333, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa2_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(17.0000, 125.3333, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa2_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-17.0000, 125.3333, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa2_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-6.6667, 108.3333, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa2_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-6.6667, 132.3333, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa2_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(6.6667, 108.3333, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa2_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(6.6667, 132.3333, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rod_faceTop_Fa2():
	FC000 = ctr_face_rod_faceTop_Fa2_Ctr0()
	FC001 = ctr_face_rod_faceTop_Fa2_Ctr1()
	FC002 = ctr_face_rod_faceTop_Fa2_Ctr2()
	FC003 = ctr_face_rod_faceTop_Fa2_Ctr3()
	FC004 = ctr_face_rod_faceTop_Fa2_Ctr4()
	FC005 = ctr_face_rod_faceTop_Fa2_Ctr5()
	FC006 = ctr_face_rod_faceTop_Fa2_Ctr6()
	FC007 = ctr_face_rod_faceTop_Fa2_Ctr7()
	FC008 = ctr_face_rod_faceTop_Fa2_Ctr8()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008])
	rOneFace.check()
	return rOneFace

def ctr_face_rod_faceTop_Fa3_Ctr0():
	P000 = App.Vector(20.0000, 160.0000, 0)
	P001 = App.Vector(20.0000, 186.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(19.4142, 187.4142, 0)
	P003 = App.Vector(18.0000, 188.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-18.0000, 188.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-19.4142, 187.4142, 0)
	P006 = App.Vector(-20.0000, 186.0000, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-20.0000, 160.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-19.4142, 158.5858, 0)
	P009 = App.Vector(-18.0000, 158.0000, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(18.0000, 158.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(19.4142, 158.5858, 0)
	P012 = App.Vector(20.0000, 160.0000, 0)
	S007 = Part.Arc(P010, P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rod_faceTop_Fa3_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(17.0000, 168.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa3_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-17.0000, 168.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa3_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(17.0000, 178.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa3_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-17.0000, 178.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa3_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-6.6667, 161.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa3_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-6.6667, 185.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa3_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(6.6667, 161.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa3_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(6.6667, 185.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rod_faceTop_Fa3():
	FC000 = ctr_face_rod_faceTop_Fa3_Ctr0()
	FC001 = ctr_face_rod_faceTop_Fa3_Ctr1()
	FC002 = ctr_face_rod_faceTop_Fa3_Ctr2()
	FC003 = ctr_face_rod_faceTop_Fa3_Ctr3()
	FC004 = ctr_face_rod_faceTop_Fa3_Ctr4()
	FC005 = ctr_face_rod_faceTop_Fa3_Ctr5()
	FC006 = ctr_face_rod_faceTop_Fa3_Ctr6()
	FC007 = ctr_face_rod_faceTop_Fa3_Ctr7()
	FC008 = ctr_face_rod_faceTop_Fa3_Ctr8()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008])
	rOneFace.check()
	return rOneFace

def ctr_face_rod_faceTop_Fa4_Ctr0():
	P000 = App.Vector(20.0000, 212.6667, 0)
	P001 = App.Vector(20.0000, 238.6667, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(19.4142, 240.0809, 0)
	P003 = App.Vector(18.0000, 240.6667, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-18.0000, 240.6667, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-19.4142, 240.0809, 0)
	P006 = App.Vector(-20.0000, 238.6667, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-20.0000, 212.6667, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-19.4142, 211.2525, 0)
	P009 = App.Vector(-18.0000, 210.6667, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(18.0000, 210.6667, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(19.4142, 211.2525, 0)
	P012 = App.Vector(20.0000, 212.6667, 0)
	S007 = Part.Arc(P010, P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rod_faceTop_Fa4_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(17.0000, 220.6667, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa4_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-17.0000, 220.6667, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa4_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(17.0000, 230.6667, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa4_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-17.0000, 230.6667, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa4_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-6.6667, 213.6667, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa4_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-6.6667, 237.6667, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa4_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(6.6667, 213.6667, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa4_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(6.6667, 237.6667, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rod_faceTop_Fa4():
	FC000 = ctr_face_rod_faceTop_Fa4_Ctr0()
	FC001 = ctr_face_rod_faceTop_Fa4_Ctr1()
	FC002 = ctr_face_rod_faceTop_Fa4_Ctr2()
	FC003 = ctr_face_rod_faceTop_Fa4_Ctr3()
	FC004 = ctr_face_rod_faceTop_Fa4_Ctr4()
	FC005 = ctr_face_rod_faceTop_Fa4_Ctr5()
	FC006 = ctr_face_rod_faceTop_Fa4_Ctr6()
	FC007 = ctr_face_rod_faceTop_Fa4_Ctr7()
	FC008 = ctr_face_rod_faceTop_Fa4_Ctr8()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008])
	rOneFace.check()
	return rOneFace

def ctr_face_rod_faceTop_Fa5_Ctr0():
	P000 = App.Vector(20.0000, 265.3333, 0)
	P001 = App.Vector(20.0000, 291.3333, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(19.4142, 292.7475, 0)
	P003 = App.Vector(18.0000, 293.3333, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-18.0000, 293.3333, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-19.4142, 292.7475, 0)
	P006 = App.Vector(-20.0000, 291.3333, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-20.0000, 265.3333, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-19.4142, 263.9191, 0)
	P009 = App.Vector(-18.0000, 263.3333, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(18.0000, 263.3333, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(19.4142, 263.9191, 0)
	P012 = App.Vector(20.0000, 265.3333, 0)
	S007 = Part.Arc(P010, P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rod_faceTop_Fa5_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(17.0000, 273.3333, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa5_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-17.0000, 273.3333, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa5_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(17.0000, 283.3333, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa5_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-17.0000, 283.3333, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa5_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-6.6667, 266.3333, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa5_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-6.6667, 290.3333, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa5_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(6.6667, 266.3333, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa5_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(6.6667, 290.3333, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rod_faceTop_Fa5():
	FC000 = ctr_face_rod_faceTop_Fa5_Ctr0()
	FC001 = ctr_face_rod_faceTop_Fa5_Ctr1()
	FC002 = ctr_face_rod_faceTop_Fa5_Ctr2()
	FC003 = ctr_face_rod_faceTop_Fa5_Ctr3()
	FC004 = ctr_face_rod_faceTop_Fa5_Ctr4()
	FC005 = ctr_face_rod_faceTop_Fa5_Ctr5()
	FC006 = ctr_face_rod_faceTop_Fa5_Ctr6()
	FC007 = ctr_face_rod_faceTop_Fa5_Ctr7()
	FC008 = ctr_face_rod_faceTop_Fa5_Ctr8()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008])
	rOneFace.check()
	return rOneFace

def ctr_face_rod_faceTop_Fa6_Ctr0():
	P000 = App.Vector(20.0000, 318.0000, 0)
	P001 = App.Vector(20.0000, 344.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(19.4142, 345.4142, 0)
	P003 = App.Vector(18.0000, 346.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-18.0000, 346.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-19.4142, 345.4142, 0)
	P006 = App.Vector(-20.0000, 344.0000, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-20.0000, 318.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-19.4142, 316.5858, 0)
	P009 = App.Vector(-18.0000, 316.0000, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(18.0000, 316.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(19.4142, 316.5858, 0)
	P012 = App.Vector(20.0000, 318.0000, 0)
	S007 = Part.Arc(P010, P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rod_faceTop_Fa6_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(17.0000, 326.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa6_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-17.0000, 326.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa6_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(17.0000, 336.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa6_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-17.0000, 336.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa6_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-6.6667, 319.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa6_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-6.6667, 343.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa6_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(6.6667, 319.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rod_faceTop_Fa6_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(6.6667, 343.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rod_faceTop_Fa6():
	FC000 = ctr_face_rod_faceTop_Fa6_Ctr0()
	FC001 = ctr_face_rod_faceTop_Fa6_Ctr1()
	FC002 = ctr_face_rod_faceTop_Fa6_Ctr2()
	FC003 = ctr_face_rod_faceTop_Fa6_Ctr3()
	FC004 = ctr_face_rod_faceTop_Fa6_Ctr4()
	FC005 = ctr_face_rod_faceTop_Fa6_Ctr5()
	FC006 = ctr_face_rod_faceTop_Fa6_Ctr6()
	FC007 = ctr_face_rod_faceTop_Fa6_Ctr7()
	FC008 = ctr_face_rod_faceTop_Fa6_Ctr8()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008])
	rOneFace.check()
	return rOneFace

def rod_faceTop():
	FA000 = face_rod_faceTop_Fa0()
	FA001 = face_rod_faceTop_Fa1()
	FA002 = face_rod_faceTop_Fa2()
	FA003 = face_rod_faceTop_Fa3()
	FA004 = face_rod_faceTop_Fa4()
	FA005 = face_rod_faceTop_Fa5()
	FA006 = face_rod_faceTop_Fa6()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005, FA006])
	rOneFig.check()
	return rOneFig

def fex_subpax_rod_rod():
	FIG = rod_faceCut()
	VEX = FIG.extrude(App.Vector(0, 0, 346))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_rod_rod = fex_subpax_rod_rod()

def fex_subpax_rod_plates():
	FIG = rod_faceTop()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 14.0000, 0.0000))
	return VFP
subpax_rod_plates = fex_subpax_rod_plates()

def fvol_pax_rod():
	V000 = subpax_rod_rod
	V001 = V000.fuse(subpax_rod_plates)
	VFC = V001.removeSplitter()
	return VFC
pax_rod = fvol_pax_rod()


pax_rod.check()
#pax_rod.exportBrep(f"{outFileName}.brep")
#pax_rod.exportIges(f"{outFileName}.igs")
#pax_rod.exportStep(f"{outFileName}.stp")
pax_rod.exportStl(f"{outFileName}.stl")

